### ISSUE TITLE
Refactor deploy script to use viem

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1006]
Currently the [deploy script](https://github.com/latticexyz/mud/blob/main/packages/cli/src/commands/deploy.ts) is using ethers to send transactions for deploying contracts and registering tables / systems / modules etc.

We're moving towards viem (see https://github.com/latticexyz/mud/issues/582) and should also use viem instead of ethers here too (eg. for more expressive errors in case a transaction fails).

We should also modularize this script, it's currently pretty spaghetti.

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/pull/1702
