### ISSUE TITLE
Cannot be deployed on arbitrum goerli

### ISSUE THREAD

**Issue by aLIEzsss4** [latticexyz/mud#1009]
Cannot be deployed on arbitrum goerli, I suspect it is a l2 sorting issue, causing the contract to not be packaged into the rollup, but it can be deployed on Mumbai.

<img width="419" alt="image" src="https://github.com/latticexyz/mud/assets/24380830/ac1cc74f-efbe-457d-8bbd-15895ba5285e">

{"jsonrpc":"2.0","id":54,"error":{"code":-32000,"message":"nonce too high: address 0xAfCA03477E5eeBAd2B0e3577D8505D6F139b11C6, tx: 10 state: 4"}}

**Comment by holic** [comment]
going to close this since it's quite old and we've since overhauled our deploy handling, nonce handling, etc.

feel free to re-open if this is still an issue
