### ISSUE TITLE
make `chainId` case insensitive in templates

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1015]
* template projects currently expect a `chainId` param, `chainid` doesn't work. We should make this case insensitive.

**Comment by 0xnaylor** [comment]
Hi, what are the steps to recreate this issue please?

**Comment by alvrs** [comment]
You can locally start a template by cloning MUD, run `pnpm install && pnpm build` to get MUD set up locally, then cd into `templates/vanilla`, run `pnpm install`, and then `pnpm dev`. That should start a local chain, deploy the contracts, and start a webserver for the client.

The reason it's currently case sensitive is this line: https://github.com/latticexyz/mud/blob/main/templates/vanilla/packages/client/src/mud/getNetworkConfig.ts#L16 (and equivalent lines in the other templates).

**Comment by 0xnaylor** [comment]
Thank you
