### ISSUE TITLE
Expose ResourceSelector functionality in System contract

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#1030]
The ResourceSelector utility functions are ubiquitous in a codebase that is using multiple namespaces. Instead of requiring users to import the ResourceSelector library throughout their code, it would be nice if this functionality was just revealed in the default mud System. 

Note that I am already doing this in my own wrapper System contract, so this would just be a quality of life improvement.

**Comment by holic** [comment]
can you clarify what you mean here? and give an example of how you're using it?

**Comment by 0xhank** [comment]
This is a major nit haha

Once a developer wants to start building with namespaces outside of root, the ResourceSelector utility functions are required essentially everywhere. I was requesting that they can be inherited within systems from the root System contract so the imports are cleaner.

**Comment by holic** [comment]
still not really following what that would look like in practice, some code snippets would help!
