### ISSUE TITLE
System interfaces are not deleted on `worldgen`

### ISSUE THREAD

**Issue by yonadaaa** [latticexyz/mud#1038]
If I delete a system, then run `worldgen`, the `ISystem` interface is not deleted. This is inconsistent with `tablegen`

**Comment by alvrs** [comment]
For `worldgen` there is the `--clean` flag you can pass to delete old files: https://github.com/latticexyz/mud/blob/main/packages/cli/src/commands/worldgen.ts#L13

For `tablegen` it automatically deletes the previous table directory: https://github.com/latticexyz/mud/blob/main/packages/store/ts/library/render-solidity/tablegen.ts#L15

Agree we should align the `worldgen` script here and automatically delete the previously generated files. We just have to make we don't accidentally delete any source files, but I believe table interfaces are always placed into the `codegen` folder so should be fine.

**Comment by dk1a** [comment]
I think `--clean` flag should just be true by default, and for some cases (like world package itself, which overrides worldgenDirectory and has some manual interfaces there) it can be set to false
