### ISSUE TITLE
useComponentValue broken in prod

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#1076]
When using the useComponentValue hook in production code (vite), I see the following error
```
TypeError: Cannot read properties of null (reading 'useState')
    at react_production_min.useState 
```

This error only shows up in prod, and can be traced to this hook (toggling the useComponentValue hook on and off creates the error).

The error still appears with matching @types/react and react versions.

@smallbraingames

**Comment by smallbraingames** [comment]
I'll second this, am also seeing this issue and have currently "fixed" by copy-pasting the hook into our client code

**Comment by holic** [comment]
Is this still an issue?
