### ISSUE TITLE
Snapsync modules is not installed automatically

### ISSUE THREAD

**Issue by noyyyy** [latticexyz/mud#1118]
context: #1117

I tried the latest mud verion(2.0.0-alpha.1.268), add `snapSync: true` and then start locally development. There is deploy SnapSyncModule contract log but no install SnapSyncModule log, unless I add `SnapSyncModule` to modules manually. Therefore, the frontend has errors like below.

```
Uncaught (in promise) Error: call revert exception [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="snapSync_system_getNumKeysInTable(bytes32)", data="0x3c2432e55ce9202400000000000000000000000000000000000000000000000000000000", errorArgs=null, errorName=null, errorSignature=null, reason=null, code=CALL_EXCEPTION, version=abi/5.7.0)
```

I think there is two ways to resolve this issue.

1. fix automatically install snapsync modules when `snapSync: true`.
2. update the example in docs like #1117

**Comment by holic** [comment]
we're removing the snap sync module for now (we have a new and improved indexer which should negate the need for it)

we may revisit snap sync in the future but have a less strong use case for it for now
