### ISSUE TITLE
Add missing events to Store (for setting partial fields) and review existing events

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1121]
see https://github.com/latticexyz/mud/pull/434#discussion_r1126366857

**Comment by alvrs** [comment]
As part of this we should rethink all Store events. If we move away from "schema index" and instead use "byte offset", we can have a general purpose indexer that is not aware of schemas, which would allow parallel processing of events.

**Comment by holic** [comment]
See also https://github.com/latticexyz/mud/issues/1222

**Comment by alvrs** [comment]
implemented in #1354
