### ISSUE TITLE
Improve handling of custom types in tablegen

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1139]
- [ ] Allow generating 1 struct for several tables with identical data, so the data can be seamlessly passed between tables
- [x] Allow generating user types from the config to be used in tables
- [ ] Allow structs to be imported from a manual user file

**Comment by alvrs** [comment]
partially fixed by #1566

**Comment by holic** [comment]
closing in favor of https://github.com/latticexyz/mud/issues/1461
