### ISSUE TITLE
MUDError: Can not fetch lastBaseFeePerGas from RPC

### ISSUE THREAD

**Issue by Osub** [latticexyz/mud#1162]
pnpm run deploy:local
```
 Deploying MUD contracts with profile localhostTestnet to RPC http://192.168.1.15:8565   fork  from  BSC

running "forge build"
[⠆] Compiling...
No files changed, compilation skipped
Initial nonce 6208
MUDError: Can not fetch lastBaseFeePerGas from RPC
 ELIFECYCLE  Command failed with exit code 1.

````

**Comment by holic** [comment]
can you post your forge version?
```
% forge --version
forge 0.2.0 (4b0d5d8 2023-07-07T00:05:43.223482000Z)
```

**Comment by Osub** [comment]
![image](https://github.com/latticexyz/mud/assets/7599190/d59e7b56-c340-42f2-9212-8713e41dce67)

**Comment by holic** [comment]
Just coming back to this - did you figure this out? One other thing I am now noticing is the RPC URL `http://192.168.1.15:8565` is different than what I'd expect of a local anvil node. How are you running anvil?

**Comment by Osub** [comment]
anvil  node  no problem
