### ISSUE TITLE
roninjin10 nits and observations

### ISSUE THREAD

**Issue by roninjin10** [latticexyz/mud#1221]
Using this issue to track nits and observations I see in Mud [building a simple app with it](https://github.com/roninjin10/lodden-thinks)

**Comment by roninjin10** [comment]
The word ambitious here is scary and might make me think that Mud is heavy complicated and hard to use 
<img width="487" alt="image" src="https://github.com/latticexyz/mud/assets/35039927/7142c71f-324e-4d26-a8f6-a400b4b91f3e">

**Comment by roninjin10** [comment]
Need a "why mud" or mud compared to alternatives type docs page imo 
<img width="230" alt="image" src="https://github.com/latticexyz/mud/assets/35039927/e797c8eb-cdfc-4c35-8ddd-bac84ce0518c">

**Comment by roninjin10** [comment]
There are 0 links to these applications 
<img width="525" alt="image" src="https://github.com/latticexyz/mud/assets/35039927/7f1689b8-75f6-4353-bf4e-8a4417256b42">

**Comment by roninjin10** [comment]
Looks like MODE is an acrynom but don't know what it stands for 
<img width="503" alt="image" src="https://github.com/latticexyz/mud/assets/35039927/27810427-d232-4164-8da4-e8c6f05ccddb">

**Comment by holic** [comment]
cc @qbzzt
