### ISSUE TITLE
move test tables out of store/world mud config

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1309]
Apps shouldn't be deploying our test tables like `Mixed` and `Vector2` and `AddressArray` such. These should get moved into some test dir.

https://github.com/latticexyz/mud/blob/5294a7d5983c52cb336373566afd6a8ec7fc4bfb/packages/store/mud.config.ts#L22-L46
https://github.com/latticexyz/mud/blob/5294a7d5983c52cb336373566afd6a8ec7fc4bfb/packages/store/mud.config.ts#L22-L46

**Comment by alvrs** [comment]
could do that by generating these manually from a script for now, like in `CLI`
