### ISSUE TITLE
gas-report: rename binary to just gas-report

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1333]
It's not MUD specific so we can rename from `mud-gas-report` to `gas-report` and let ~anyone use it.

**Comment by dk1a** [comment]
what do you think about a separate repo for it? (the package could still be `@latticexyz/gas-report`) It is indeed completely standalone and we could reduce our package number a bit.
btw I called it `mud-gas-report` mostly as an analogy to `mud gas-report` (the only way it could be called before the new package), no strong reason for that name

**Comment by holic** [comment]
I think we should continue to publish packages from the monorepo, even if they could technically exist standalone.
