### ISSUE TITLE
Add custom filters when doing queries

### ISSUE THREAD

**Issue by aymericdelab** [latticexyz/mud#1363]
Following @alvrs comment here: https://discord.com/channels/865335009915961364/1029021716367806514/1144301124447371344

Goal would be to create a "Filter" query fragment that takes a component as first parameter and a filter function as second parameter. 

Steps to make this would be:
1. Add new fragment type here: https://github.com/latticexyz/mud/blob/main/packages/recs/src/Query.ts
2. Add a case to passesQueryFragment
3. Add it to isPositiveFragment 

Example:

```
// only retrieve entities that have a position x and y bigger than 1000
let entities = runQuery([Has(Position), Filter(Position, ({x, y}) => x > 1000, y > 1000)]);
```

**Comment by holic** [comment]
this will be happening via #2272
