### ISSUE TITLE
Consider merging `call` and `callFrom`

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1395]
And always expect a `delegator` in `call`. Should be cheap enough to check if `delegator == msg.sender` and bypass the delegation stuff.

**Comment by holic** [comment]
Maybe it makes sense to keep `call` as a UX thing and just allow `callFrom` to accept `msg.sender` as `delegator` (instead of raising), then our tooling can just default to using `callFrom` everywhere (and provide the correct `delegator` based on how the client is connected).

**Comment by alvrs** [comment]
> Maybe it makes sense to keep call as a UX thing and just allow callFrom to accept msg.sender as delegator (instead of reverting), then our tooling can just default to using callFrom everywhere (and provide the correct delegator based on how the client is connected).

I think that makes sense! Keeping `call` is nice from a rollup gas perspective because it saves some calldata if `msg.sender == from`
