### ISSUE TITLE
Refactor registerNamespace() to not check if space already exist when called from registerSystem()

### ISSUE THREAD

**Issue by haythemsellami** [latticexyz/mud#1424]
`registerSystem()` checks if the namespace do not exist, and then call `registerNamespace()` which do the same check again.

I think `registerSystem()` could be refactored to save a tiny gas, by making a call to an internal `_registerNamespace()` that does not have the name space existent check.

`_registerNamespace()` could also be used by the public `registerNamespace()`.

**Comment by holic** [comment]
`registerSystem` now requires the namespace to be registered and does not automatically register it if it does not exist
