### ISSUE TITLE
make sure the world contract can't be registered as a system / reconsider `requireOwnerOrSelf`

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1447]
- We need to make sure the world contract's address can't be registered as a system
- We need to check if `requireOwnerOrSelf` (which considers external calls of the world to itself the same as internal calls) introduces security issues

**Comment by holic** [comment]
This is done via

https://github.com/latticexyz/mud/blob/b0c45f87305b7ae80c43a4c09c084cdfc8066f48/packages/world/src/World.sol#L54-L65
