### ISSUE TITLE
The indexer only cares about a single world is a chain

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#1506]
1. Create fresh installation.
    ```sh
    git clone https://github.com/latticexyz/mud.git && cd mud && pnpm install && pnpm build
    cd ..
    pnpm create mud@main app
    # I selected vanilla, but it shouldn't matter
    ```
    
1. Run the app.
    ```sh
    cd app; pnpm dev
    ```
    
1. Wait until the app is initialized.

 1. In a separate command line, run the indexer (with sqlite).
    ```sh
    cd mud
    cd packages/store-indexer
    pnpm start:sqlite:local
    ```
    
1. Get the list of worlds.
     ```sh
     curl 'http://localhost:3001/trpc/findAll?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22chainId%22%3A31337%2C%22address%22%3A%220x5FbDB2315678afecb367f032d93F642f64180aa3%22%7D%7D%7D' | jq '.[0].result.data.json.tables[].address' | sort | uniq
      ```
      
       There is only one world, which is correct.
       
1. In a separate command line, deploy another world.

   ```sh
    cd app/packages/contracts
    pnpm deploy:local
    ```

    
1. Wait a minute and run the command to get the list of worlds. There is still only one.
    
     ```sh
      sleep 60 ; curl 'http://localhost:3001/trpc/findAll?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22chainId%22%3A31337%2C%22address%22%3A%220x5FbDB2315678afecb367f032d93F642f64180aa3%22%7D%7D%7D' | jq '.[0].result.data.json.tables[].address' | sort | uniq
      ```
      
When I ran the test, the new `World` was deployed in block 1357:      
```json
{
      worldAddress: '0xB7f8BC63BbcaD18155201308C8f3540b07f84F5e',
      blockNumber: 1357
}
```

But it was still not detected as block 1663:

```
0x6d756473746f726500000000000000005461626c65730000000000qbzzt@Oris-MacBook-Pro store-indexer % curl 'http://localhost:3001/trpc/findAll?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22chainId%22%3A31337%2C%22address%22%3A%220x5FbDB2315678afecb367f032d93F642f64180aa3%22%7D%7D%7D' | jq '.[0].result.data.json.blockNumber'       
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 26425  100 26425    0     0  2448k      0 --:--:-- --:--:-- --:--:-- 4300k
"1674"
```

**Comment by holic** [comment]
This is because your tRPC query contains a world address, which is filtering your results. The indexer tRPC doesn't support "give me all data for all worlds" at the moment - we would want to turn this off in production but there's some API questions around that that I don't feel like we have time to figure out at the moment.

If you watch the indexer logs (`DEBUG=mud:*`), you'll see when you deploy the new world, all the events from the deploy get picked up as expected.
