### ISSUE TITLE
The indexer gets stuck with PostgreSQL

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#1507]
This is on MacOS with PostgreSQL 15.

1. Clear the database.
  
   ```sh
   cd ~/Library/Application\ Support/Postgres
   rm -rf var-15 
   ```

1. Start the database UI and click **Initialize**.

1. Create fresh installation.
    ```sh
    git clone https://github.com/latticexyz/mud.git && cd mud && pnpm install && pnpm build
    cd ..
    pnpm create mud@main app
    # I selected vanilla, but it shouldn't matter
    ```
    
1. Run the app.
    ```sh
    cd app; pnpm dev
    ```
    
1. Wait until the app is initialized.

 1. In a separate command line, run the indexer.
    ```sh
    cd mud
    cd packages/store-indexer
    pnpm start:postgres:local
    ```

     Wait until it is `all caught up`.

1. Get the last block indexed from the indexer.
   
    ```sh
    curl 'http://localhost:3001/trpc/findAll?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22chainId%22%3A31337%2C%22address%22%3A%220x5FbDB2315678afecb367f032d93F642f64180aa3%22%7D%7D%7D' | jq '.[0].result.data.json.blockNumber'
    ```

1. Wait a few minutes and run the same command again, see the results are unchanged.
    ```sh
    curl 'http://localhost:3001/trpc/findAll?batch=1&input=%7B%220%22%3A%7B%22json%22%3A%7B%22chainId%22%3A31337%2C%22address%22%3A%220x5FbDB2315678afecb367f032d93F642f64180aa3%22%7D%7D%7D' | jq '.[0].result.data.json.blockNumber'
    ```

To see in PostgreSQL:

1. Open the `psql` app
2. `select * from __mud_internal.chain;`
3. Wait a few minutes
4. `select * from __mud_internal.chain;`

Again, you'll see an unchanged value.

**Comment by holic** [comment]
Thanks for the good repro steps! Fix is up: https://github.com/latticexyz/mud/pull/1514
