### ISSUE TITLE
use event reference instead of defining twice

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1580]
IStore and StoreCore both define store events, but since #1473, we should be able to reference these from one place

However, we'll wanna ensure that these events still appear in the ABIs (they should)

Also should update tests to reference these instead of redefining

**Comment by alvrs** [comment]
It would be nice to emit events from `IStoreEvents` from `StoreCore`, but there seems to be a known bug in solc for 0.8.21 that prevents it: https://github.com/ethereum/solidity/issues/14430 - it's merged, but i don't think a version including the fix has been released yet

**Comment by holic** [comment]
sounds like foundry team suggests just skipping 0.8.21 and using 0.8.22: https://github.com/foundry-rs/foundry/issues/6206#issuecomment-1792934780

**Comment by holic** [comment]
we did this in https://github.com/latticexyz/mud/pull/2356 and https://github.com/latticexyz/mud/pull/2348
