### ISSUE TITLE
declarative deployments

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1611]
Given a mud config, systems, etc. and an optional world address, we should be able to figure out what needs to be deployed (missing tables, updated systems, etc.) and turn our deploy process from imperative to declarative.

**Comment by ludns** [comment]
i think it would be good to have an hour long jam on this (along with maybe a larger tooling discussion)

**Comment by holic** [comment]
we should probably do #1006 and #1636 first

**Comment by ludns** [comment]
I think #1636 <https://github.com/latticexyz/mud/issues/1636> is easier
when we have the primitives for declarative deployment.

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/pull/1702
