### ISSUE TITLE
improve changesets releases for next

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1660]
we're currently hitting what looks like github rate limits when changesets attempts to do a snapshot release (https://github.com/changesets/changesets/issues/1239), probably because we have _so many_ changesets queued up

we could probably take some inspiration from wagmi's alpha release pipeline?
https://github.com/wagmi-dev/wagmi/commit/ceb8ddfdb2a0d17645dc516b2b1c7e51709a2aea

**Comment by alvrs** [comment]
Seems like the issue is the `get-github-info` query (https://github.com/changesets/changesets/blob/main/packages/get-github-info/src/index.ts)

**Comment by holic** [comment]
not really an issue now that we're out of prerelease mode
