### ISSUE TITLE
registerSystem should check if system conforms to interface

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1701]
We expect a `WorldContextConsumer` in `registerSystem`:
https://github.com/latticexyz/mud/blob/08d7c471f9a2f4d6c237641eea316313d010373c/packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol#L110

But we cast to `address` everywhere it's referenced in the method.

- I assume the more specific `WorldContextConsumer` is there for our tests and so the compiler can help us identify issues, but should the `registerMethod` also check `system.supportsInterface(WORLD_CONTEXT_CONSUMER_INTERFACE_ID)`?
- Should this be `System` instead of `WorldContextConsumer`?
- Would bad things happen if we register a system contract that doesn't conform to these interfaces? If not, should we just make the type `address`?

**Comment by alvrs** [comment]
That check happens here: https://github.com/latticexyz/mud/blob/08d7c471f9a2f4d6c237641eea316313d010373c/packages/world/src/modules/core/implementations/WorldRegistrationSystem.sol#L117

The System interface is currently just an alias for WorldContextConsumer without additional methods.

Bad things would happen if the contract was not a system: you could make the World call arbitrary contracts (don't have a specific attack vector in mind, calling the World itself is not possible anymore, but still feels dangerous and unintended).

**Comment by holic** [comment]
oh awesome, missed that!
