### ISSUE TITLE
after TransactionExecutionError: Execution reverted for an unknown reason. I cannot send any tx

### ISSUE THREAD

**Issue by demirbey05** [latticexyz/mud#1714]
You can reach the reproduced repo from here: https://github.com/demirbey05/mud-repro . I used a standard template. 

I captured a screen video when I reproduced it; you can see the video in the attachments. My thesis was after revert errors, I could not execute any tx. In this video, I have added a decrement function for decrementing Counter by one. I know that EVM will revert if there is an underflow issue. So I created a bunch of decrement tx at the time when the counter value is 0. All of them reverted and I could execute the increment successfully but at the second trial, the increment tx started to give me an error. After refreshing I can continue my progression. 

You can reach video from here : https://drive.google.com/file/d/1_wwudHxVCxfS6l1To9E7GA_OpWr3oXxs/view?usp=sharing
If you could not access the video, you can reach me via telegram @demirbey05

**Comment by demirbey05** [comment]
This issue is stemming from foundry.

**Comment by ardasevinc** [comment]
> This issue is stemming from foundry.

Clarification: the issue is resolved after updating foundry to latest version.
