### ISSUE TITLE
generate type definitions for systems

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1743]
when we have [better config parsing](https://github.com/latticexyz/mud/issues/1668), we'll be able to reference system IDs by their name within the mud config, e.g.

```
config.systems.MySystem.systemId
worldConfig.systems.CoreSystem.systemId
```

this is useful in things like `callFrom` and `batchCall` where you need to provide a system ID and it's less ergonomic to have to generate them and hardcode the system names

in this world, it would be great if these keys were strongly typed

**Comment by holic** [comment]
If we're headed in the direction of using interfaces for config input/output types, we might have something that looks like

```ts
interface System {
  ...
}

interface ConfigOutput {
  systems: Record<string, System>
}
```

I wonder if we could extend that with a `systems.d.ts` file that adds to the interface like
```ts
interface ConfigOutput {
  systems: {
    MoveSystem: { ... },
    AttackSystem: { ... },
  }
}
```

**Comment by dk1a** [comment]
We can't really merge nested stuff, so would need separate interfaces for each level that needs to be overridden
Something like:
```ts
interface System {
  ...
}
interface Systems {
  [key: string]: System
}
interface ConfigOutput {
  systems: Systems
}

interface MoveSystem extends System {
  ...
}

interface Systems {
  MoveSystem: MoveSystem,
  AttackSystem: System & { ... },
}
```

**Comment by holic** [comment]
closing in favor of https://github.com/latticexyz/mud/issues/1743
