### ISSUE TITLE
add support for "replacement transaction underpriced"

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#1776]
There is a chance between simulating, incrementing nonce, and then sending the tx to the mempool that the nonce was used (e.g. in another process using the same private key). Sending the tx will throw/revert with "replacement transaction underpriced"

We should catch these errors in our `sendTransaction` and `writeContract` helpers and retry, the same way we do for nonce errors during simulation.

**Comment by alvrs** [comment]
fixed by #3180
