### ISSUE TITLE
Deployment to multiple chains failed because maxPriorityFeePerGas was undefined

### ISSUE THREAD

**Issue by singyiu** [latticexyz/mud#1779]
Hi MUD team,
I was deploying mud world to Polygon's zkevm chain
but run into the following error because maxPriorityFeePerGas was undefined.

```
at /Users/sing/playground/web3/mud/mud-playground-03/node_modules/.pnpm/@ethersproject+wallet@5.7.0/node_modules/@ethersproject/wallet/lib/index.js:163:116
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'invalid object key - maxPriorityFeePerGas',
  code: 'INVALID_ARGUMENT',
  argument: 'transaction:maxPriorityFeePerGas',
  value: {
    nonce: 5,
    maxPriorityFeePerGas: undefined,
    maxFeePerGas: undefined,
    gasPrice: BigNumber { _hex: '0x02faf080', _isBigNumber: true },
    ...
    type: 0,
    gasLimit: BigNumber { _hex: '0x154f47', _isBigNumber: true },
    chainId: 1442
  }
```

Reproduced with a new "pnpm create mud@next" project with the mud+threejs template (@latticexyz/cli 2.0.0-next.11)
with chain profiles added to foundry.toml
i.e.
```
[profile.zkevm-testnet]
eth_rpc_url = "https://rpc.public.zkevm-test.net"
```
and setting deployer PRIVATE_KEY in .env

Deployment to lattice-testnet was working fine.
But the same error was thrown for deploying to other chains like zkevm-testnet, scroll-testnet and mantle-testnet.
Setting gas_limit and gas_price in foundry.toml did not help.

Most likely a mud cli deploy script issue. And so reporting it here.
Thanks team.

**Comment by holic** [comment]
Going to close this in favor of https://discord.com/channels/865335009915961364/1163125391091838977 for now until we get to the bottom of the root issue!
