### ISSUE TITLE
Add `isInstalled` to `Module`

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1852]
> side note/not blocking: since we're starting to use this more, might be nice to lift this into `Module` as a helper function e.g. `isInstalled()` or `isInstalled(module)` and `requireNotInstalled()`

_Originally posted by @holic in https://github.com/latticexyz/mud/pull/1789#discussion_r1378758582_

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/pull/2056
