### ISSUE TITLE
update `mud faucet` CLI to use the new faucet

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1893]

**Comment by holic** [comment]
I think our old testnet infra still uses the old gRPC faucet, which is why I've avoided updating this. We haven't opened up the newer testnets/infra to folks yet.

**Comment by holic** [comment]
since we're not intending to run a public faucet for Redstone Holesky, I wonder if we should just remove the faucet command?

or are we going to have a Redstone Devnet?

**Comment by holic** [comment]
I removed the faucet command/usage for now: https://github.com/latticexyz/mud/pull/2811

I wanna rethink our faucet API (i.e. not trpc) before we expose it more broadly.
