### ISSUE TITLE
export production code compiled with tsc for docker images

### ISSUE THREAD

**Issue by ludns** [latticexyz/mud#1895]
currently, the indexer and faucets are executed via `pnpm tsx` which transpiles typescript code on the fly. It's great for development, not great for production.
Ideally we should be able to bundle that to optimized javascript and execute with an optimized runtime like bun.

**Comment by holic** [comment]
There should be prebuilt binaries in there too!

```
packages/store-indexer/node_modules/dist/bin/postgres-indexer.js
packages/store-indexer/node_modules/dist/bin/postgres-frontend.js
packages/store-indexer/node_modules/dist/bin/sqlite-indexer.js
packages/faucet/node_modules/dist/bin/faucet-server.js
```

**Comment by holic** [comment]
fixed in https://github.com/latticexyz/mud/pull/1900
