### ISSUE TITLE
mud deploy fails if there is no system

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#1924]
deployer expects the `System.json` abi to be available in the forge output, but it's only if it is referenced somewhere in the project
<img width="1009" alt="CleanShot 2023-11-12 at 21 01 00@2x" src="https://github.com/latticexyz/mud/assets/89248902/782e4fb2-45f1-44b2-b551-757fd2fb8ac7">

**Comment by holic** [comment]
fails here: https://github.com/latticexyz/mud/blob/712866f5fb392a4e39b59cd4565da61adc3c005f/packages/cli/src/deploy/resolveConfig.ts#L40

**Comment by holic** [comment]
no longer an issue after reworking system deploys for multi-namespace support
