### ISSUE TITLE
cli tool to decode abi-encoded MUD errors

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#2087]
Currently MUD errors in a CLI are often printed like this:

```
Error: 
(code: 3, message: execution reverted, data: Some(String("0xfbf10ce673794444444400000000000000000000455243323052656769737472790000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000002473793a444444440000000000000000000000003a4552433230526567697374727900000000000000000000000000000000000000000000000000000000000000")))
```

We should figure out a way to either make `forge`/`cast` aware of the MUD abi to automatically decode the errors, or create a separate CLI tool to decode errors like this based on the MUD abi.

Currently the manual workaround is to run `forge selectors list`, find the error based on the first four bytes of the printed error bytes, then manually decode the remaining error bytes with the error's ABI.

**Comment by holic** [comment]
I think this is solved with our inclusion of all Store/World errors in ABIs, so going to optimistically close this
