### ISSUE TITLE
Id vs ID

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#210]
Call me pedantic, but the capitalization of ID vs Id is confusing me as it is different in various places throughout the codebase.

For example, `ComponentDevSystem` uses `componentId` and `chainId` is the typical usage but otherwise `ID` is capitalized in almost every case.

Just a little thing -- I personally prefer Id instead of ID

**Comment by alvrs** [comment]
I kinda agree since `Id` is an abbreviation and not an initialism (like `IP`). (You could argue it's pronounced like an initialism though). We can't change the naming in the current version because it's a breaking change, but we can make a note for the next breaking version of MUD.

**Comment by FlynnSC** [comment]
+1 for `Id` over `ID` everywhere

**Comment by holic** [comment]
We're moving towards `Id` everywhere.
