### ISSUE TITLE
dedupe world's `AccessControl` and world-modules' `AccessControlLib`

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2104]
they're the same file

since we already import/depend on world from world-modules, maybe we remove the world-modules one?

**Comment by yonadaaa** [comment]
They are actually slightly different, according to [this comment](https://github.com/latticexyz/mud/blob/main/packages/world-modules/src/utils/AccessControlLib.sol#L12-L13) in `AccessControlLib`.

```
 * This library is functionally equivalent with the AccessControl library from world,
 * but uses StoreSwitch instead of always reading from own storage.
 ```

**Comment by holic** [comment]
I bet we could consolidate though, with one `AccessLib` and methods like `hasAccess` (using `StoreSwitch`) and `_hasAccess` (using `_`-prefixed methods)

**Comment by holic** [comment]
closing as a dupe of https://github.com/latticexyz/mud/issues/1853
