### ISSUE TITLE
Check if namespaces exist in access control checks

### ISSUE THREAD

**Issue by yonadaaa** [latticexyz/mud#2105]
It was recently [suggested](https://github.com/latticexyz/mud/pull/2095#discussion_r1447172656) that the `requireAccess` function should explicitly check if the namespace exists using: 

```solidity
ResourceIds.getExists(toNamespaceId))
```

This would ensure any access control checks on non-existent namespaces revert, which is expected because no one has access to them yet. This prevents any "premature" interactions like sending ETH to an unregistered namespace.

However this is a hot code path so this check would add some gas overhead.

**Comment by alvrs** [comment]
i'd prefer to keep those checks unbundled so we can more granularly use them (ie only check existence of a namespace once, but then require multiple actors to have access to it)

**Comment by holic** [comment]
> i'd prefer to keep those checks unbundled so we can more granularly use them (ie only check existence of a namespace once, but then require multiple actors to have access to it)

Do we have places where we do multiple access checks? What's the cost of a "warm" look up of the namespace existing?
