### ISSUE TITLE
FieldLayout.validate should never allow empty

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2112]
We don't have any usages of `allowEmpty` for `FieldLayout`, so should we remove this option?

https://github.com/latticexyz/mud/blob/f3d1ac8d9aa3152e50182021fa564a505e214ad1/packages/store/src/FieldLayout.sol#L148-L152

**Comment by holic** [comment]
@dk1a are there any legit uses of an empty FieldLayout in terms of validating?

**Comment by dk1a** [comment]
It's a remnant from when we only had Schema, which can be empty for keys (singleton stuff, I think we still have that? not sure)
I can't think of a use for an empty FieldLayout, though I doubt it breaks things either
Safe to remove imo
