### ISSUE TITLE
bump solc to >= 0.8.22

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2120]
https://github.com/ethereum/solidity/blob/develop/Changelog.md

I want this fix:
> NatSpec: Fix internal error when requesting userdoc or devdoc for a contract that emits an event defined in a foreign contract or interface.

I can't recall where I ran into this but it was a really annoying bug.

And this is nice:
> Allow defining events at file level.

Could consider bumping to a later version but nothing jumps out at me as a need.

**Comment by yonadaaa** [comment]
We can wait until Foundry supports 0.8.24: https://github.com/foundry-rs/foundry/issues/6903
