### ISSUE TITLE
syncToZustand is slow to hydrate from indexer snapshot

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2141]
https://discord.com/channels/865335009915961364/1196402713341218826

I assume this is similar to what we saw a while back with RECS where the hydration step takes a while because it triggers updates for each record/value, which lead us to an option that can disable this depending on sync state: https://github.com/latticexyz/mud/blob/main/packages/store-sync/src/recs/syncToRecs.ts#L36-L37

I think what we need to do is update this: https://github.com/latticexyz/mud/blob/main/packages/store-sync/src/zustand/createStorageAdapter.ts

instead of calling `store.setState` for each log, we could turn all the logs into records to be set, then call `store.setState` once at the end of the loop with all the records

**Comment by holic** [comment]
repro here: https://github.com/dudendy/mud-primodium-snapshot

**Comment by dudendy** [comment]
@holic resolved in #2145
