### ISSUE TITLE
Add global `using` statement for `WorldResourceId`

### ISSUE THREAD

**Issue by yonadaaa** [latticexyz/mud#2143]
Similar to https://github.com/latticexyz/mud/pull/2135

**Comment by aditya520** [comment]
Since `WorldResourceIdInstance` and `ResourceId` are in different packages, I believe we can't use `global` for them.
It can be done if we import `world` into `store`, which I believe is not the best design pattern as it will create a `cyclic dependency`. 🤔  
@yonadaaa @holic

**Comment by holic** [comment]
You're right:

![Image](https://github.com/latticexyz/mud/assets/508855/68e0edc7-a20c-4a58-91fc-84667032146d)

I wonder if there's room for moving this into e.g. a "common" package to import into each and avoid cyclic dependencies, or if we should keep each type in their respective packages and keep using world resource IDs in the verbose way.
