### ISSUE TITLE
make namespace usage consistent with double underscore

### ISSUE THREAD

**Issue by frolic** [latticexyz/mud#2173]
We're now using a double underscore delimiter for namespaced function signatures (`{namespace}__{functionName}`) and may need to update other areas to be consistent with this change:
- SQL table names/schemas
- MUD config output and TS types
- human-readable resource IDs (currently uses colon as a delimiter)

**Comment by holic** [comment]
I think this is good enough. The rest will come with the config refactor (#1668)
