### ISSUE TITLE
Flaky storage adapter test

### ISSUE THREAD

**Issue by yonadaaa** [latticexyz/mud#2203]
This test has been failing by time out recently. Restarting fixes it. https://github.com/latticexyz/mud/actions/runs/7695357200/job/20968050919?pr=2202

![image](https://github.com/latticexyz/mud/assets/29184158/25daf6e7-7474-4199-b8f2-43c19a849a58)

**Comment by holic** [comment]
just saw this too 🤔  wonder why this only just started appearing

**Comment by holic** [comment]
I think this started happening recently because we updated the generated test data (logs) after a long period of not updating this file, and all the new logs means the tests take slightly longer than before, tipping it over the default timeout (5s).

Bumped this in #2223
