### ISSUE TITLE
WorldFactory: allow creator to pass in salt

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2214]
follow up to https://github.com/latticexyz/mud/pull/2210

> could we allow the sender to pass the salt themselves? so final salt is msg.sender + their salt 
reason is: we might want some world address for the same world on multiple chains, and it might be the case that worldCount is different on different chains

> not sure i have time right now, but it's pretty simple: instead of worldCounts[msg.sender]++ being part of the final salt calculation, it's a value passed by the caller as a function arg.
reason is: worldCount is already a form of value controlled by the sender, but it's annoying to "set it" because the only way to change it is to deploy worlds through that contract.
CREATE2 already reverts if a contract currently exists at that address, so I think we should let people pass whatever salt they want; both preventing them from being frontran by including the msg.sender in the salt and letting them pass whatever extra value they want (enabling the same world address on multiple chains)

**Comment by holic** [comment]
Should we always require a salt in `deployWorld`? or is it useful to have a code path for an incrementing count that computes its own salt?

**Comment by partylikeits1983** [comment]
> It might be useful to add a function parameter of bytes 'salt' to the WorldFactory.deployWorld function to help facilitate consistent deployment of world addresses across different networks.
> 
> Something like this might be useful [here](https://github.com/latticexyz/mud/blob/6470fe1fd1fc73104cfdd01d79793203bffe5d1c/packages/world/src/WorldFactory.sol#L33):
> 
> ```solidity
> function deployWorld(bytes memory userSalt) public returns (address worldAddress) {
>    // Deploy a new World and increase the WorldCount
>    bytes memory bytecode = type(World).creationCode;
>    uint256 salt = uint256(keccak256(abi.encode(userSalt, msg.sender, worldCounts[msg.sender]++)));
>    worldAddress = Create2.deploy(bytecode, salt);
>    IBaseWorld world = IBaseWorld(worldAddress);
> 
>    // Initialize the World and transfer ownership to the caller
>    world.initialize(coreModule);
>    world.transferOwnership(ROOT_NAMESPACE_ID, msg.sender);
> 
>    emit WorldDeployed(worldAddress);
>  }
> ```
> 
> if there is a contract already deployed at that address, create2 would revert.

lmk if I should open a PR w this

**Comment by holic** [comment]
> lmk if I should open a PR w this

After some internal chat, we're thinking of nixing the notion of a world counter and just take in a bytes salt with each deploy call. Feel free to PR it!
