### ISSUE TITLE
replace entity id hex strings with base64 strings

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#222]
Right now entity ids (which are uint256 on the contracts) are stored as hex strings on the client. We need to convert entity ids to strings to use them as key in objects/maps. But converting to hex wastes memory, because javascript stores strings with 2 bytes per character, but hex only utilizes 16 characters. Instead we should use a base64 string encoding for entity ids on the client and convert it back to hex/bigint just before sending it to the contract.

**Comment by holic** [comment]
I don't think this is relevant anymore.
