### ISSUE TITLE
Better wallet support

### ISSUE THREAD

**Issue by tash-2s** [latticexyz/mud#2256]
This is a tracking issue for the better wallet support project, aiming to improve Ethereum account management in MUD for an enhanced developer experience, leading to a better end-user experience.

Below are the project details shared by @alvrs. Additional information and progress will be posted/updated as comments on this issue and related PRs/issues.

## Project Details

**Context**: MUD provides templates to kickstart new projects. The templates provide basic scaffolding like the network setup, connection with local state libraries, and wallet management. As part of the templates, a random session wallet is generated for the user and stored in local storage, which allows transactions in the session to be executed without requiring the user to confirm each time. In order to execute transactions on a chain with non-zero gas fee the user has to transfer balance to the session wallet (or receive it from a faucet).

There are a couple areas for improvement here:

- The current scaffold of the templates makes it non-trivial to add support for external wallets and allow users to switch their external wallet. It’s possible (ie Sky Strife did it) but it requires some workarounds and there is an opportunity to update the scaffold with native support for external wallets that can be switched.
- MUD has support for account delegation, which allows a main wallet to delegate permissions to interact with a World to a session wallet. However, the setup of such an account delegation from main wallet to session wallet currently has to be done manually by the developer. There is an opportunity to design libraries that make this much easier and include them in the default template.
- The session wallet is currently randomly generated and stored in local storage, which makes it easy to lose. Instead we could add a mechanism to derive a session wallet from a signature of the main wallet, which would make it impossible to lose the session wallet and make it possible to “log in” with the same session wallet in a new session (by signing the same message with the same main wallet in the new session).
- Currently the developer has to transfer a small amount of ETH to the session wallet to allow the session wallet to pay for gas. In an ideal world we could avoid this step by integrating MUD with some account abstraction standard that supports paymasters. The main wallet could still generate a session wallet to sign actions for the account abstraction relayer to avoid having to confirm every transaction, but the session wallet wouldn’t require its own funds to pay for gas.

**Comment by tash-2s** [comment]
## Deliverables and Tasks

- [ ] 1. Support for external wallets and wallet switching
	- Estimated duration: ~1 week?
	- TODO: Link an issue or PR here
- [ ] 2. Helper for account delegation for session wallet
	- Estimated duration: <1 week?
- [ ] 3. Persistent session wallet (so users won't lose the session accounts)
	- Estimated duration: >1 week?
- [ ] 4. Mechanism to remove the need for balance transfers to session accounts

**Comment by tash-2s** [comment]
I discussed this with @alvrs and @holic last week. Here are the notes:

- For item 1, "external wallets" refers to wallet applications (e.g., MetaMask) and the EOAs.
- For item 3, the idea is like this: a main account signs a specific message, and then the signature is used as the private key for a session account.

**Comment by tash-2s** [comment]
For 3., the persistent session wallet, I might want to consider allowing users to create multiple derived session accounts as they wish, although I haven't fully thought through this aspect yet. Since session accounts are much easier to leak compared to main accounts, users might want the ability to revoke the delegation of the old session account and switch to a new one.

**Comment by alvrs** [comment]
Closing as outdated, replacing with more granular issues for account kit
