### ISSUE TITLE
Support for external wallets in templates

### ISSUE THREAD

**Issue by tash-2s** [latticexyz/mud#2260]
- This issue is part of https://github.com/latticexyz/mud/issues/2256

# Motivation

Currently, the templates generated by the `create-mud` command use internal burner wallets in the clients. To facilitate non-local environments, developers are required to manually integrate external wallet connections.

Having external wallet support into the templates would be beneficial. This issue is aimed at achieving that goal.

# Possible implementation options

Several approaches can be considered.

## External wallet support options

Note: `wagmi` is a React library that internally utilizes the vanilla JavaScript library `@wagmi/core`.

Major libraries supporting wallet connections include:

- [`@rainbow-me/rainbowkit`](https://www.rainbowkit.com/): Styled React components built on `wagmi`. Used by Sky Strife and Redstone websites.
- [`connectkit`](https://docs.family.co/connectkit): Styled React components built on `wagmi`.
- [`@rabby-wallet/rabbykit`](https://rabbykit.rabby.io/): Styled UI built on `@wagmi/core`.
- [`@web3modal/wagmi`](https://docs.walletconnect.com/web3modal/about): Styled UI built on `@wagmi/core`.
- [`wagmi`](https://wagmi.sh/react/guides/connect-wallet#build-your-own): React Hooks built on `@wagmi/core`.
- [`@wagmi/core` (and `@wagmi/connectors`)](https://wagmi.sh/core/api/connectors): A vanilla JavaScript library.
- [`mipd`](https://github.com/wevm/mipd): JavaScript utilities for [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) by the wevm team. This is used in `@wagmi/core`. The retrieved Ethereum providers can be used for [the `viem`'s client custom transport](https://viem.sh/docs/clients/wallet#json-rpc-accounts). Although the conventional `window.ethereum` ([EIP-1193](https://eips.ethereum.org/EIPS/eip-1193)) still works with viem, it's not recommended due to limitations in multi-wallet support. Most wallets are [compatible](https://github.com/WalletConnect/EIP6963/blob/4754abdef8a30ceb74d1126e131fee2e08dbd611/src/utils/constants.ts) with EIP-6963.

## Options for integrating external wallets into templates

The objective is to maintain the current user experience in existing templates, which are designed to work out-of-the-box without necessitating external wallets.

Options include:

- Creating new templates that use external wallets instead of the existing burner wallets.
- Updating existing templates to support both external wallets and burner wallets.

Ideally, the `create-mud` command would allow users to choose their preferences for various aspects (e.g., react or vanilla, burner or external wallet, wagmi or rainbowkit, ecs or something). However, this requires improvement to template management and `create-mud`, which I'd like to work on a separate project if desired.

# Proposed solution

For the external wallet connection, I'd like to use `@wagmi/core` for vanilla templates and `wagmi` for react templates. This approach is preferred as it's less-opinionated and does not add any new dependencies, since developers are likely to use Wagmi in their projects. I will not include support for [the WalletConnect v2 protocol](https://specs.walletconnect.com/2.0/specs/clients/sign/), as it requires a project ID for setup. Developers can [add the support later](https://wagmi.sh/core/api/connectors/walletConnect) easily.

For the integration of external wallet support into templates, I'd like to create new templates (`vanilla-external-wallet` and `react-external-wallet`) that include this feature, thereby not impacting existing templates. As the better wallet support project advances, I plan to update these new templates continually. Once it's ready, I'll apply the wallet support into the existing templates and remove the newly added ones. An alternative approach could be starting with implementations in the `examples/` directory before rolling them out to the templates. I don't think combining the existing burner wallets and external wallets within the same client is a good idea due to the complexity it introduces. Wagmi does not effectively manage providers and burner wallets together, so the client code would need additional wallet management logic.

**Comment by tash-2s** [comment]
## Open Questions

How should we continue supporting the burner wallet feature in our templates?

I'll bring the main account (from an external wallet) and session account mapping feature to the templates as my next task in the project, which reduces the friction of signing transactions multiple times. It's a more realistic setup but still requires an external wallet to be installed. I am thinking about whether we want all templates to include the burner wallets which work without external wallets.

**Comment by holic** [comment]
Closing in favor of https://github.com/latticexyz/mud/issues/2852
