### ISSUE TITLE
Throw warning when systems have same prefixes

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#2263]
When two system names have identical prefixes up to index 16, there is an occasional bug in the deploy script where one of the systems doesn't register properly to the world. The revert thrown when calling the system excludes a message and the bug occurs at different rates depending on the environment (20-50%).

**Comment by holic** [comment]
This line has the list of systems we're targeting for deploy:
https://github.com/latticexyz/mud/blob/8193136a9511d066aeebce82155d3509aa760282/packages/cli/src/deploy/resolveConfig.ts#L45

We should just be able to iterate through `systems` and check of there are any overlapping `systemId`s. Eventually we'll wanna move this to our config parsing/resolving, but this can wait until #1668.
