### ISSUE TITLE
Move LibDeploy.ejs to MUD and improve deploy CLI

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#236]
- Remove project setup assumptions from MUD CLI
- Move LibDeploy.ejs / codegen for deployment to MUD instead of individual project repos

**Comment by cha0sg0d** [comment]
@alvrs we tweaked `LibDeploy.ejs` for some custom deploy logic around tick stuff. Maybe it's good to keep this file inside the project itself 🤷

**Comment by alvrs** [comment]
The idea is to move it to mud by default (so it stays in sync with changes to mud), but provide a command for projects to "eject" to move stuff like this into the project itself

**Comment by dk1a** [comment]
Just added #309, it seems relevant to mention here for removing project setup assumptions
