### ISSUE TITLE
add system signatures to FunctionSignatures

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2382]
we have a use case in dev tools for decoding `callFrom` with a world function selector where we want to ultimately display the system function signature in our "action logs"

it would help to be able to look up these signatures onchain as needed

(related to #2386)

**Comment by yonadaaa** [comment]
fyi in Sky Strife there is a [transaction explorer](https://github.com/latticexyz/skystrife-public/blob/main/packages/client/src/app/amalgema-ui/Transactions.tsx#L241-L250) that displays the function names of `call`, `callFrom` and `batchCall` calls. It uses the world contracts [`onWrite`](https://github.com/latticexyz/skystrife-public/blob/main/packages/client/src/mud/setupNetwork.ts#L100-L104) hook though so it doesn't have to work back from a selector

**Comment by holic** [comment]
decided we'll just do "add system signatures" part for now and avoid the cost of onchain tables until we have a good use case for it

**Comment by holic** [comment]
while we do this, we should also rename `functionSelector` key to `worldFunctionSelector` in `FunctionSelectors` table

so that it's clear that `FunctionSelectors` table are for world function selectors (and can be used as source of truth for generating world ABI)

while `FunctionSignatures` is just a generic registry for offchain stuff (translating ~any function selector to signature and back)

**Comment by holic** [comment]
added in https://github.com/latticexyz/mud/pull/2392
