### ISSUE TITLE
Register/unregister delegates via delegate call + delegator signature

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#2383]
## Proposal
Allow the following flow for initializing an account delegation:
1. User controls a low risk account (A) and wants to interface with MUD using a high-risk 'session account' (B)
2. User signs a message with A that states it is giving B delegation access
3. B submits a tx registering/unregistering B as a delegate to A. A's signature is attached. 
4. MUD confirms the signature is valid and grants execution of the delegation function.
5. Delegation proceeds as normal.

## Why
Primodium's biggest onboarding hurdle has been players running into every bug imaginable to submit the first tx to spawn and delegate (in our case these calls are batched). Some issues include:
- Chain id not recognized (WalletConnect/Coinbase)
- CoinId not recognized (okx)
- Unknown Ethereum Address when clicking play
- Transaction failed
ETC.

It would greatly improve UX and streamline our user flow.

**Comment by yonadaaa** [comment]
Adding signatures is getting closer full-blown account abstraction, IMO. We should see if we can generalise this and/or integrate with EIP's like [ERC4337](https://www.erc4337.io/)

**Comment by alvrs** [comment]
Added in #2480 (for now in an optional module, moving to the core world contract once audited)
