### ISSUE TITLE
How mud implement the moving system

### ISSUE THREAD

**Issue by rubb1sh** [latticexyz/mud#240]
Frequent updates of coordinate states are not possible to implement in a smart contract. Since updating a smart contract requires gas, I'm curious how mud implements recording and updating character coordinates.

**Comment by alvrs** [comment]
I assume you refer to OPCraft's position sync? We used the MUD relayer, which can distribute signed messages off-chain: https://github.com/latticexyz/opcraft/blob/main/packages/client/src/layers/noa/systems/createRelaySystem.ts#L128-L137
