### ISSUE TITLE
Tables with Enum as key don't work properly for enum values >=10

### ISSUE THREAD

**Issue by JakubGrzegowski** [latticexyz/mud#2401]
We are trying to set Buildings table, and in next line use same _building parameter for setting offchain event, but when setting Buildings using input (10, true, 50) it is treated as the input was (0, true, 50). This is happening only when _building is >= 10, and everything works fine for _building < 10. We detected this issue by simply subscribing to Buildings and PlayerDonated tables and noticing that outputs do not match. Using MUD v14

I'll try to provide an MRE using MUD starter template, also feel free to ask me q's if you need any additional information

**mud.config.ts**
```
    Buildings: {
      keySchema: {building: "BuildingType", isTeamRight: "bool"},
      dataStruct: true,
      valueSchema: {
        totalResourcesStaked: "uint256[5]",
      }
    },

    PlayerDonated:{
      valueSchema:{
        player: "address",
        isTeamRight: "bool",
        building: "BuildingType",
        resources: "uint256[5]",
      },
      offchainOnly: true,
    },
```

**BuildingSystem.sol**
```
    function contributeToBuilding(BuildingType _building, uint256[5] memory _resources) public {
(...)
        Buildings.set(_building, isTeamRight, buildingResources);
        PlayerDonated.set(0, player, isTeamRight, _building, _resources);
(...)
```

**Comment by holic** [comment]
A reproduction would be great. It sounds like there's more to this than just the onchain piece you noted here, as in the issue you're seeing surfaces in the sync data in the client?

**Comment by JakubGrzegowski** [comment]
> A minimal reproduction would be great. It sounds like there's more to this than just the onchain piece you noted here, as in the issue you're seeing surfaces in the sync data in the client?

Yes, the client is our output source in this case

**packages/client/src/index.ts**
```
(...)
        PlayerDonated.update$.subscribe((update) => {
            console.log("PlayerDonated", update);
            this.player_donated(update);
        });
(...)
        Buildings.update$.subscribe((update) => {
            console.log("Buildings", update);
            this.buildings(update);
        });
(...)
```

**Comment by yonadaaa** [comment]
@JakubGrzegowski I tried to reproduce this locally and didn't get this issue 🤔 

Some questions:
- What does your `BuildingType` enum look like? How many members does it have?
- Are you syncing by RPC or indexer?
- Does this happen if you remove `PlayerDonated`, and do absolutely nothing except set `Buildings`?

**Comment by JakubGrzegowski** [comment]
@yonadaaa Gm, I also could not reproduce this behavior in MRE. We investigated this issue, and we found that the error was very deep on our side, causing improperly conversion of incoming updates key values from hex. Sorry for misunderstanding

**Comment by holic** [comment]
Sounds like this is a non-issue on our end, so gonna close this out! Feel free to reopen if you can reproduce!
