### ISSUE TITLE
Use Ownable std implementation for all ownable MUD contracts (Component, System, Set, MapSet))

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#245]
We should have a way for the current owner to update the owner. We also might consider inheriting from Ownable in one of the standard set of solidity libraries (OpenZeppelin, etc.)

_Originally posted by @holic in https://github.com/latticexyz/mud/issues/244#issuecomment-1311798971_

**Comment by dk1a** [comment]
I was thinking of Ownable from https://github.com/solidstate-network/solidstate-solidity during #239, but wanted to limit the scope of that PR to minor interface and inheritance refactoring. OZ doesn't comply with erc173, and I prefer solidstate for upgradeability.
If u want I can do another PR with the lib and add it to set and mapset while I'm at it

**Comment by alvrs** [comment]
that would be amazing!

**Comment by holic** [comment]
> OZ doesn't comply with erc173

How so? Looks like the interface matches up exactly.

**Comment by dk1a** [comment]
> > OZ doesn't comply with erc173
> 
> How so? Looks like the interface matches up exactly.

It's about transferring to 0
See comments in https://github.com/OpenZeppelin/openzeppelin-contracts/pull/2874
