### ISSUE TITLE
Remove the "md" type from `resourceToHex`

### ISSUE THREAD

**Issue by yonadaaa** [latticexyz/mud#2526]
We should remove the module "md" type from resourceToHex as it's no longer used in Solidity
https://github.com/latticexyz/mud/blob/main/packages/common/src/resourceToHex.ts#L12

**Comment by yonadaaa** [comment]
Also we should add tests to prevent this from happening again

**Comment by holic** [comment]
wasn't sure how to add tests for this but went ahead and removed the `md` value in  https://github.com/latticexyz/mud/pull/2955
