### ISSUE TITLE
Naming a field 'type' breaks tablegen

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#2560]
The following table cannot be generated:

```
Score: {
      key: ["entity", "type"],
      schema: { entity: "bytes32", type: "uint8", value: "uint256" }, 
   },
```

This error message should be improved and the naming issue should be caught in the typechecking.

![image](https://github.com/latticexyz/mud/assets/71292860/b0a8fdca-69fb-4c75-9703-ad2f01829627)

**Comment by holic** [comment]
related to #580

**Comment by Osub** [comment]
Naming a field 'is' breaks tablegen

**Comment by holic** [comment]
closing in favor of https://github.com/latticexyz/mud/issues/1396
