### ISSUE TITLE
templates: remove build step from deploy scripts

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2582]
https://github.com/latticexyz/mud/blob/66865c57c5c6f9c3bc070cf108bbc05e816790c2/templates/react/packages/contracts/package.json#L9-L10

this happens automatically inside `mud deploy`

https://github.com/latticexyz/mud/blob/66865c57c5c6f9c3bc070cf108bbc05e816790c2/templates/react/packages/contracts/package.json#L11

can also change this to `mud dev-contracts`

then the scripts look a lot cleaner and more consistent:
```json
"build": "mud build",
"clean": "forge clean && rimraf src/codegen",
"deploy:local": "mud deploy",
"deploy:testnet": "mud deploy --profile=lattice-testnet",
"dev": "mud dev-contracts",
```

**Comment by blackbeard002** [comment]
Hello @holic, can I take this up?
