### ISSUE TITLE
Addition of option to fetch from indexer even  for synchronization after initialize

### ISSUE THREAD

**Issue by hourglasshoro** [latticexyz/mud#2628]
# Proposal

Currently, the indexer is only used to retrieve initialBlockLogs
https://github.com/latticexyz/mud/blob/main/packages/store-sync/src/createStoreSync.ts#L92

I want to suppress the number of requests from the client to the RPC endpoint via publicClient, so I would like to use logs via indexer in `storedBlock$` as well
https://github.com/latticexyz/mud/blob/main/packages/store-sync/src/createStoreSync.ts#L194

I would like to get it by specifying the start and end block number like `fetchAndStoreLogs`, but it does not exist in the indexer query, so I need to modify it to include the indexer as well.

https://github.com/latticexyz/mud/blob/main/packages/store-sync/src/fetchAndStoreLogs.ts#L10
https://github.com/latticexyz/mud/blob/main/packages/store-indexer/src/postgres/queryLogs.ts

**Comment by holic** [comment]
Stay tuned! We’ve got #2272 coming soon, which will allow steaming from the indexer.

**Comment by 0x-shanks** [comment]
Thank you!
