### ISSUE TITLE
change nonce manager to fetch transaction count from "latest" instead of "pending"

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#2676]
Only reason to use "pending" imo is for letting the mempool do nonce queueing for you, but it makes it hard to recover from nonce gaps (bc "getTransactionCount" with block tag "pending" doesn't give you the missing nonce to full the gap). Since the nonce manager is used to queue nonces instead of the mempool, it should use "latest" to be able to recover from nonce gaps in "resetNonce"

**Comment by holic** [comment]
I wonder if it would make sense to initialize the nonce manager with `latest` but use `pending` any time we need to reset, so we don't override a bunch of txs and have cascading "replacement transaction underpriced" errors (#2675)

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/pull/3180
