### ISSUE TITLE
registerTable should check for existence of table ID for both table types

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2710]
basically I want a unique constraint on (namespace, name) not (table type, namespace, name)

otherwise it's possible to register both an offchain and onchain table with the same namespace+name, making indexing with decoded tables more annoying (because type now needs to be part of the table name, or we drop one of the two tables)

**Comment by yonadaaa** [comment]
This is on the Store level, so it's more a constraint on `type`, and a bytes30 `name`.
