### ISSUE TITLE
find consistent way to run mprocs

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2770]
`pnpm mprocs` seems to fail in some environments (specifically in some MacOS environments, maybe related to rosetta vs not)

**Comment by karooolis** [comment]
One of the machines where this happens. `pnpm mprocs` fails silently.

![image2](https://github.com/user-attachments/assets/a972181a-61ac-455e-932a-cebeb03f81be)
![image](https://github.com/user-attachments/assets/7a712ff4-249b-46ab-95ad-526e6eb083cd)
