### ISSUE TITLE
add vscode settings to templates

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2795]
to ensure vscode uses the project's TS version:
```
{
  "typescript.tsdk": "node_modules/typescript/lib"
}
```

**Comment by roaminro** [comment]
@holic I just had a look at the templates and they all seem to have that settings set in the `/.vscode/settings.json` file.

This issue can be closed ;)

**Comment by holic** [comment]
you're right! this was done in https://github.com/latticexyz/mud/pull/2389
