### ISSUE TITLE
add IncrBy/DecrBy function for integer

### ISSUE THREAD

**Issue by chuwt** [latticexyz/mud#2806]
Increments or decrements the number stored at key.
Very useful for add/sub integer like balance.

**Comment by holic** [comment]
any reason for a specific function for this when you can just do
```solidity
Table.setCount(Table.getCount() + 1)
```

**Comment by chuwt** [comment]
Yes, but it sometimes becomes duplicate when there are too many keys like:
```
Table.setCount(key1, key2, key3, Table.getCount(key1, key2, key3) + 1)
# would be good if we support incrBy
Table.incrByCount(key1, key2, key3, 1)
```
Anyway, just an advanced feature.

**Comment by holic** [comment]
Appreciate the feedback, but we don't have plans to expand the table API surface area in this way.
