### ISSUE TITLE
Feedback for “Add a system”

### ISSUE THREAD

**Issue by ryanalbrecht** [latticexyz/mud#2861]
Im still very new to this but there is a slight error in the code when using the default setup with the HelloWorld tutorial.

createSystemCall.ts should be `app_decrement()` instead of `decrement()` as the generated function name in packages\contracts\src\codegen\world\IDecrementSystem.sol is prefixed with `app__`

```  
const decrement = async () => {
  const tx = await worldContract.write.app__decrement();
  await waitForTransaction(tx);
  return getComponentValue(Counter, singletonEntity);
};
```

**Comment by qbzzt** [comment]
Thank you. `decrement()` used to be correct, but then we changed the templates and didn't change the guide to match. I apologize. I just submitted a PR to fix this: https://github.com/latticexyz/mud/pull/2859 .
