### ISSUE TITLE
add base `MudScript` to inherit from

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#2884]
the base script could do things we tend to always do

- read world address from env or `worlds.json` (based on chain ID)
- read deployer PK from env
- set store address

**Comment by yonadaaa** [comment]
similar to https://github.com/latticexyz/mud/issues/1755#issuecomment-1759408440

**Comment by holic** [comment]
closing in favor of https://github.com/latticexyz/mud/issues/1755
