### ISSUE TITLE
Enable JS tracing on RPC

### ISSUE THREAD

**Issue by joalavedra** [latticexyz/mud#2904]
Hi, I'm trying to deploy our infra to support 4337 on mud but I see your RPC don't support js tracing and this is a limitation for some bundler providers.

**Comment by holic** [comment]
are you referring to Redstone RPC? and what do you mean by JS tracing?

**Comment by joalavedra** [comment]
Hi @holic we want to make smart account compatible with 4337 (https://eips.ethereum.org/EIPS/eip-4337#rpc-methods-debug-namespace) and the `debug_traceCall` is required

**Comment by holic** [comment]
closing as a Redstone issue, not a MUD issue

will bubble up to the team

**Comment by holic** [comment]
sounds like we won't be enabling `debug_traceCall` for now, but you can run a node to get what you're looking for: https://redstone.xyz/docs/run-node
