### ISSUE TITLE
Can we have a `forge options` command line option on `mud deploy`?

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#2906]
In https://discord.com/channels/865335009915961364/1252619258760790016 we see a case where `forge script PostDeploy` fails, but a `forge script Post Deploy --gas-estimate-multipler 200` is successful. We can't have a command line parameter for every `forge` and `cast` parameter, but it would be helpful if in this kind of case we were able to have a general one so we could specify:

```
mud deploy .... --forge-opts '--gas-estimate-multiplier 200'
```

Instead of telling users to run the script manually.

**Comment by holic** [comment]
We have this already: https://github.com/latticexyz/mud/pull/2703
