### ISSUE TITLE
Creating a singleton table with only a dynamic length field doesn't work

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#2983]
From my `mud.config.ts` file:

```typescript
    Event: {
      schema: {
//        id: "bytes32",
        message: "string",
      },
      key: [],
    },
```    

This does not generate a table. However, if I uncomment the `id` field it does.

**Comment by holic** [comment]
Are you seeing any errors?

**Comment by qbzzt** [comment]
My mistake. I don't have any idea why it didn't work before, but it's working now. Sorry.
