### ISSUE TITLE
Redo the `mud.config.ts` page

### ISSUE THREAD

**Issue by qbzzt** [latticexyz/mud#2994]
Ludens: so as we need to do a bunch of doc work on namespaces here https://mud.dev/config; it would be good to bundle that with a lot of different examples of MUD configs and breaking them down cc @Ori Pomerantz
i was trying to explain a MUD config to someone and that page in the doc is one of the most lacking

Frolic: agreed! I think this page could become more of a guide on how to get started with the config (single vs multiple namespaces, how to use each top-level key, etc.)

then a sub page that ideally is generated from the TS doc that explains each config option so we don't have to keep em in sync
the config on this page is wrong anyway! overdue for an update

**Comment by holic** [comment]
gonna consider this done for now
