### ISSUE TITLE
add documentation for action system and optimistic components

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#304]
I have had trouble understanding how these concepts work in relation to the rest of the client -- documentation on `Mud.dev` would be useful

**Comment by alvrs** [comment]
For reference, here is the source code for the action system: https://github.com/latticexyz/mud/tree/main/packages/std-client/src/systems/ActionSystem

And here for optimistic components: https://github.com/latticexyz/mud/blob/main/packages/recs/src/Component.ts#L282-L397

**Comment by qbzzt** [comment]
Does anybody object to closing this? I don't even know what optimistic components are, so I assume we don't have them.
