### ISSUE TITLE
Add Wheel Listener to PhaserX createInput

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#305]
I want to make the scroll wheel zoom in and out but I'm unable to using PhaserX because the wheel property isn't exposed 😢

**Comment by 0xhank** [comment]
Also mud should not automatically define behavior for pinching and wheeling, as different applications will want to modify them. Instead it makes sense to place them in the `createInputSystem` file of the mud starter repo.

**Comment by holic** [comment]
phasex has moved to https://github.com/latticexyz/phaserx
