### ISSUE TITLE
Documentation: ERC-721 module registration is confusing

### ISSUE THREAD

**Issue by ludns** [latticexyz/mud#3134]
The explanation for registering the ERC-721 module implicitly assume the reader knows `0x44444444` maps to "DDDD"
Consider explaining how we got this value for the MUD config, or using Viem utils to casting "DDDD" as a JS string to the corresponding hex value. I also suggest using a better name, like "MyToken" or something. 

![CleanShot 2024-09-08 at 12 37 48@2x](https://github.com/user-attachments/assets/8e3f68ba-823e-42bd-93ba-3a43077ea5c6)

**Comment by qbzzt** [comment]
> The explanation for registering the ERC-721 module implicitly assume the reader knows `0x44444444` maps to "DDDD" Consider explaining how we got this value for the MUD config, or using Viem utils to casting "DDDD" as a JS string to the corresponding hex value. I also suggest using a better name, like "MyToken" or something.

I used `DDDD` on purpose, because it makes identifying resource IDs in the namespace easier. I'll add an explanation of why I did it.
