### ISSUE TITLE
Documentation: "Deploy to blockchain" doesn't link to a guide, and instead to the `mud deploy` reference

### ISSUE THREAD

**Issue by ludns** [latticexyz/mud#3135]
This links redirects to https://mud.dev/cli/deploy instead of the actual guide
![CleanShot 2024-09-08 at 12 37 21@2x](https://github.com/user-attachments/assets/bad7b115-d248-4fd5-8579-7f1891d2830a)

**Comment by qbzzt** [comment]
I think I put this in because somebody didn't realize how to do it, but there was nothing for me to say beyond what's already in the CLI docs.

**Comment by ludns** [comment]
I think the redirect is confusing. If I think something is broken or buggy, it's not right.
Maybe it could be a very simple page saying that deploying to blockchain is mostly automated, that one can use the CLI (with a link to the docs), and a series of command to deploy the world built in this "Hello World" non-linear tutorial?
Like 1) let's fill up our Foundry profile for Garnet 2) Use mud deploy (and btw here are the docs) 3) Wait and save our worlds.json for our Frontend
