### ISSUE TITLE
Documentation: in "Replicating onchain state", add a callout explaining that you should never have to do this yourself and this is just an illustration

### ISSUE THREAD

**Issue by ludns** [latticexyz/mud#3140]
In https://mud.dev/guides/replicating-onchain-state

Additionally:
> MUD provides much of this out of the box. It uses a [familiar data model](https://mud.dev/store/data-model) with tables and fields, built on a standardized storage protocol. This lets us provide you with an [automatic indexer](https://mud.dev/services/indexer), no code is necessary to use it. And because it's all standardized, our client libraries already know how to get your app's onchain state and keep your frontend [in sync with the chain](https://mud.dev/guides/replicating-onchain-state).

Quote found in https://mud.dev/introduction. The "in sync with the chain" links to this "Guide". I think we should either link to something else (what is the best page that demonstrates "syncing to the client?", maybe it could be the top-level page of the badly named "State Query". It would explain in abstract how different parts of MUD enable clients to query the state and keep it up to date, then link to individual implementations for different programming languages)

**Comment by qbzzt** [comment]
I'm also adding a templates page (a summary of the templates) because I need to link to it.

**Comment by qbzzt** [comment]
> Quote found in https://mud.dev/introduction. The "in sync with the chain" links to this "Guide". I think we should either link to something else (what is the best page that demonstrates "syncing to the client?", maybe it could be the top-level page of the badly named "State Query".

The initial plan was to have "State sync" that explains synchronization, and "State query" that explains how to query the information. But @holic didn't have time to write State sync, and I didn't have the knowledge, so it got dropped.

For now I'm just removing the link in the introduction. I think "our client libraries already know how to get your app's onchain state and keep your frontend in sync with the chain" is clear enough. 

It would be good to write a fuller description of how client synchronization works. But I think that should wait until stash and dozer are out.
