### ISSUE TITLE
Documentation: for Dozer queries in the Dozer page, have them as SQL blocks (and not just JSON) for better formatting. Add querying with the `dozer` CLI for each example.

### ISSUE THREAD

**Issue by ludns** [latticexyz/mud#3144]
Dozer binaries (not yet published -- for now they need to be built manually on your computer. We will have `dozerup` at release) enable querying SQL directly with a nice interface and introspecting tables.

For all example queries in the [Dozer page](https://mud-docs-hb1c75puf-latticexyz.vercel.app/state-query/dozer) (and in future content like #3143 #3142) we should have two tabs (maybe we need a new component for that): 
1. Query with Dozer CLI 
2. Query with CURL. 
 
Option 1) will be much more readable as we'll use SQL code block instead of JSON, and the output is formatted nicely.

**Comment by qbzzt** [comment]
> Dozer binaries (not yet published -- for now they need to be built manually on your computer. We will have `dozerup` at release) enable querying SQL directly with a nice interface and introspecting tables.
> 
> For all example queries in the [Dozer page](https://mud-docs-hb1c75puf-latticexyz.vercel.app/state-query/dozer) (and in future content like #3143 #3142) we should have two tabs (maybe we need a new component for that):
> 
> 1. Query with Dozer CLI
> 2. Query with CURL.
> 
> Option 1) will be much more readable as we'll use SQL code block instead of JSON, and the output is formatted nicely.

How do I get the dozer CLI?

**Comment by qbzzt** [comment]
Not relevant until the dozer CLI is generally available, which isn't happening yet.
