### ISSUE TITLE
CLI call-system natural inputs

### ISSUE THREAD

**Issue by JirAcheron** [latticexyz/mud#317]
It the CLI already supports calling a system using `system[Id|Address]`, `--args` and `--argTypes`. Extending that functionality, a "natural language" input with some argument parsing would significantly smoothen that experience.

e.g.
```bash
$ mud call-system --??? mud.System.ConfirmTrade(uint: {charID}, uint: {tradeLogID})
```
in this example the ConfirmTrade system is called using uint inputs charID and tradeLogID, as specified by the type casting. taking this one step further, we could imagine:

```bash
$ mud call-system --??? mud.System.ConfirmTrade({charID}, {tradeLogID})
```
type inference could be achieved (when none is provided) by relying on the abi jsons found in `contracts/src/abi/` or an equivalent source generated during build. using that same source we could probably achieve something like:

```bash
$ mud call-system --??? ConfirmTrade({charID}, {tradeLogID})
```
as an ideal format for calling systems through the CLI

**Comment by holic** [comment]
closing for now as I don't think we'll get to this any time soon
