### ISSUE TITLE
CLI report on entities with call-system

### ISSUE THREAD

**Issue by JirAcheron** [latticexyz/mud#318]
this one's probably better explained with a visual:
```bash
$ mud call-system --systemId ConfirmTrade --args ...
EntityID 91
| Component | Value |
| --------- | ----- |
| State | 'Complete' |
| Requester | 19 |
| Requestee | 27 |

EntityID 92
| Component | Value |
| --------- | ----- |
| State | 'Confirmed' |
| TradeLogID |  91 |

EntityID 97
| Component | Value |
| --------- | ----- |
| State | 'Confirmed' |
| TradeLogID |  91 |
```

This could probably be achieved now by defining and calling a System that takes in an entity ID as input, but integrating this into the `call-system` workflow would really help tighten the feedback loop on any manual testing. Imagining either a config file that keeps track of entity IDs to report on 
```bash
$ mud config add watched-entities 91,92,97
$ mud call-system --systemId ConfirmTrade --args ...
EntityID 91
| Component | Value |
...
```

or a flag for listing those entities

```bash
$ mud call-system --systemId ConfirmTrade --args ... --entities 91,92,97
```

**Comment by holic** [comment]
closing as I don't think we'll get to this any time soon
