### ISSUE TITLE
Add a BigInt option to recs Type

### ISSUE THREAD

**Issue by FlynnSC** [latticexyz/mud#324]
Currently you can use `Type.String` and `defineStringComponent` to handle large numbers like uint256s client-side, but this means that you have to convert them to `bigint`s any time you want to do arithmetic with them, and then convert them back to a `string` if you want to save the new value. Having the ability to get and set `bigint`s directly to/from the component would be nicer.

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/commit/29fefae43d96b107a66b9fd365b566cb8c466f8b
