### ISSUE TITLE
General way to link non-component/non-system contracts into the mud deployment process

### ISSUE THREAD

**Issue by FlynnSC** [latticexyz/mud#325]
I have two use cases currently:
1. ZK proof verifier contracts auto-generated by `snarkjs` from `circom` circuits. They are just standard solidity contracts with a `verifiyProof` function.
2. Poseidon hash function contracts (with various input counts), which actually take the form of raw bytecode that is generated by a `circomlibjs` function. Currently I am copying this bytecode directly into a `PoseidonSystem` and then deploying it with an assembly `create()` call in the system constructor.

For both of these cases, I think it makes the most sense to store the resulting contract addresses in an `AddressComponent`, but I am wondering what the best way is to include the creation of these contracts into the mud deployment process, or non-standard use cases like this more generally?

**Comment by dk1a** [comment]
[FunctionBareComponent](https://github.com/latticexyz/mud/blob/main/packages/std-contracts/src/components/FunctionBareComponent.sol) is perhaps more useful here than AddressComponent

**Comment by holic** [comment]
we now support public/linked libs: https://github.com/latticexyz/mud/pull/1910
