### ISSUE TITLE
mud test verbosity doesn't work

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#326]
the verbosity flag in `mud test` sometimes doesn't work, and sometimes it does. It seems forge may cache the preferred verbosity level.

For example:  
After running the command `yarn test -v`, the script executes: 
![image](https://user-images.githubusercontent.com/71292860/211041815-f58e8b8f-59da-470d-8b17-a7f62bc11a8a.png)

For now, my workaround is stating verbosity in the `--forgeOpts` param instead.

**Comment by alvrs** [comment]
The param passed to `mud test` directly accepts a number and defaults to 2:
https://github.com/latticexyz/mud/blob/80afd1acc60c6b0e0a630a2ae0ecd5e925ef4122/packages/cli/src/commands/test.ts#L19

Eg `mud test -v 3`. 
If the `-vvv` syntax is preferred, you can pass it as a `--forgeOpts` flag
