### ISSUE TITLE
Unintended behavior around view functions in tests

### ISSUE THREAD

**Issue by d-s-i** [latticexyz/mud#3306]
https://github.com/d-s-i/activate-test-fail/tree/main

Here is the repo with steps to reproduce.

I have a GuildSystem with a view function `isMember`. 
This function call revert with `StateChangeDuringStaticCall` in test if called on its own but passes if during the test there is a write function.

I think it is unintended behavior as simply calling a view function shouldn't result in a StateChangeDuringStaticCall error.

In my test I have two test

1- `test_activate` which simply call the `isMember` function through the world (and after in comment through the table directly which passes)
2- `test_isMember` which also calls the `isMember` function through the world but this time with a write function called as well during the test. This time the function don't revert.

Probably an error somewhere in the world ?

**Comment by vdrg** [comment]
Thanks for reporting, closing this in favor of https://github.com/projectawakening/world-chain-contracts/issues/267
