### ISSUE TITLE
ABDKMath64x64 used in noise package but isn't a dependency

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#334]
![image](https://user-images.githubusercontent.com/71292860/211402647-59156802-e118-46a0-a318-166b485ca42c.png)
Upon adding the mud noise package, this error appears. This is because ABDKMath64x64 isn't a dependency of noise despite using it in `Perlin.sol`

**Comment by 0xhank** [comment]
wait it is in the packages... digging further

**Comment by holic** [comment]
It might be missing in remappings? https://github.com/latticexyz/mud/blob/main/packages/noise/remappings.txt

See others as an example: https://github.com/latticexyz/mud/blob/main/packages/std-contracts/remappings.txt
