### ISSUE TITLE
deployment of contracts to an existing world fails due to over rate limit error 

### ISSUE THREAD

**Issue by 0xxlegolas** [latticexyz/mud#3342]
Deploying a contract to an existing world in a local anvil node is generally successful; however, attempting to deploy contracts to an existing world to a public/remote chain consistently results in a rate limit error.

Error Details: 
```
 details: '{"code":-32016,"message":"over rate limit"}',
      docsPath: undefined,
      metaMessages: [Array],
      shortMessage: 'HTTP request failed.',
      version: '2.21.19',
      body: [Object],
      headers: [HeadersList],
      status: 429,
      url: 'https://rpc.garnetchain.com'
    },
```

![image](https://github.com/user-attachments/assets/c1bf5830-330a-41d9-842e-6d99f9d201e7)

**Environment:**

RPC Endpoint: https://rpc.garnetchain.com
Contract Address: 0x94b6ec3d701d10657e890b7ca51a5b059c9cc846 (deployed in Garnet)

**Steps to Reproduce:**
Deploy any contract to the existing world at 0x94b6ec3d701d10657e890b7ca51a5b059c9cc846 using the public Garnet endpoint.

**Comment by 0xxlegolas** [comment]
@holic

**Comment by ludns** [comment]
I think we could turn off rate limiting till we switch to Peroxide and have a better sense of how to rate limit this properly. ProxyD is hard to work with and I am pretty confused as to why it rate limits so heavily in some cases but not others. We could try bumping the values up again.
