### ISSUE TITLE
PhaserX setComponent best practice

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#340]
I am confused about how to use setComponent for PhaserX objects.

The problem: I want to initialize a set of values for an object that will granularly update later. I see a couple ways of doing this:

1. Create a new phaserX object component for each phaser attribute and update each individually in each update.
      My concern is this is a lot of extra code, especially for phaser objects with many attributes
2. Use one phaserX object component throughout the codebase for a single phaser object. Whenever any phaser object attribute needs to be updated, the same phaserX component is updated each time.
3. Update the same phaser object attribute across different phaserX object components. 
      I'm not sure if this will cause re-render issues as different phaserX components will conflict.

Which of these, if any, would you recommend?

**Comment by holic** [comment]
closing as we've moved out phaserx: https://github.com/latticexyz/phaserx
