### ISSUE TITLE
Proposal: Actions

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#342]
_This is mostly in an idea phase rather than a well-formed proposal. Hoping to start a discussion around use cases and potential solutions._

There are many cases in which you might want to know when certain actions are being taken by players, that may or may not result in component updates, e.g. a player attacks another player and misses.

We have a system call stream, but it's just a different view on component updates (grouped by system calls), so it depends on a component updates being emitted for the system call to propagate to clients.

This also means that you have to infer what happened based on component updates, essentially duplicating logic on the client that already exists in the contracts (source of truth). "Attack system was called, and player health lowered, so they must have landed a hit and taken damage." We could expand the system call stream to include _all_ system calls, but it still requires inferring behavior in the client, and streaming this data from the RPC node isn't as efficient as filtering on events.

For cases where you might want to "listen" to things like a "missed attack", you can create/update an arbitrary component to get it into the system call stream, and then check that no damage was done (or however you model your combat system), but this feels more like a workaround and adds a lot more gas.

I'd like to propose we have some generic Solidity event type that you can emit from systems (and/or is emitted automatically on `execute` calls) that can represent named actions. Then expose an action stream so that UIs can trigger animations, effects, etc. We can create some patterns that help guide folks away from one-off modeling and preferring ECS where possible, but I think the cases above just can't be modeled well in our current setup with system call stream, etc.

**Comment by dk1a** [comment]
I really like this.
The main problem with emitting events in systems is that when you reregister it, the events are lost. But I think that's not an issue here, since events are short-lived UI helpers (unlike e.g. ERC20 events, which are an important source of client data).
I suggest an event prefix:
```solidity
event SystemAction__Attack(uint256 indexed entity, uint256 dealtDamage, uint256 resistedDamage);
event SystemAction__SkillUse(uint256 indexed entity, uint256 skillEntity);
// etc...
```
- Always having an entity first (which would just be a convention) would allow some default clientside filtering by said entity. And you would always need at least 1 entity; even for truly global events there's a singletonEntity.
- A single `event SystemAction(uint256 indexed entity, bytes args);` means having to store the events schema somewhere, which is complicated, so multiple events with free arguments seem far easier both for MUD devs and MUD implementers.
- The client must know the abi for events, but that's not an issue, and that requirement already kinda exists (e.g. system types require it).
- A prefix (as opposed to just using all events emitted by systems) allows some events to be not-actions for whatever reason. The only not-action system events I can think of atm are ERC-compatibility ones, e.g. `Transfer` emitted by [ERC721BaseSystem](https://github.com/dk1a/solecslib/blob/main/contracts/token/ERC721/ERC721BaseSystem.sol)

**Comment by holic** [comment]
If each event has a different name/signature, it'd make it harder to filter the event stream - you'd have to set up log filters for each event type, making the system call stream essentially opt-in on a per-event basis. That's not necessarily a bad thing, just calling it out.

Alternatively, could follow something that's more like a JS event emitter, where we have a generic event type and an action name (with whatever namespacing scheme you decide on, similar to component/system ID schemes):

```solidity
event SystemAction(string indexed indexedActionName, string actionName, uint256 entityId, bytes data);
```
(Both `indexedActionName` and `actionName` are provided here because an indexed dynamic-length string is hashed before indexing, so we need both to support filtering and reading the string from the event logs.)

We could limit action names to 32 characters to fit in an indexed `bytes32`, but that seems like a pretty strong limitation.

```solidity
event SystemAction(bytes32 indexed actionName, uint256 entityId, bytes data);
```

Another point of tension is that some events may affect multiple entities (e.g. an RTS) and might be kinda gassy to emit an event per entity, but it's also a pain to construct an array in Solidity.

**Comment by dk1a** [comment]
> If each event has a different name/signature, it'd make it harder to filter the event stream - you'd have to set up log filters for each event type

Event names/signatures are just another (albeit quite special) log topic (indexed datum).
Usually the first topic is implicitly filtered by, but that's not necessary if you want all the events of a contract (and quite easy to do in ethers I think).
(For a good explanation of event logs and their topics see https://docs.ethers.org/v5/concepts/events/)

By having `string indexed indexedActionName` you're basically wasting the 1st topic and using the 2nd topic to do its job.
`bytes32(bytes("combat:miss"))` is basically what's done by the compiler to the event names (which are turned into the 1st topic, and their names stored in the abi json).
recs or std-client can provide filter functions that abstract away parsing system abi, getting all the prefixed events and all that. 

> Another point of tension is that some events may affect multiple entities (e.g. an RTS) and might be kinda gassy to emit an event per entity

That would be bad. I meant `indexed entity` as a scoping mechanism of sorts.
Imagine an rts with 100 matches of 5 players each, all of them getting all the events for each others actions.
But if you have the `entity` as matchEntity, then only the 5 ppl within the match get each others events.
It would be very use-case-specific.

All the other entities can and should also be part of the event data.
Depending on what `entity` means in your system, you could either have:
```solidity
event SystemAction_CombatMiss(uint256 indexed entity, uint256 attackerEntity, uint256 defenderEntity);
```
or 
```solidity
event SystemAction_CombatMiss(uint256 indexed entity, uint256 defenderEntity);
```

**Comment by holic** [comment]
Coming back to this again, I am realizing that I haven't made use of the return values from system `execute` functions. That would help with my immediate needs (e.g. an enum that defines the hit, miss, flee result types, possibly with corresponding data for each type).

That said, for complicated system calls that may have lots of potential actions/results, it still might be hard to do via return types and events seem like a better abstraction.

**Comment by holic** [comment]
@dk1a has started prototyping an approach for this in #665 using existing v2 protocol/infra 🎉  Shoutout to @yonadaaa and @Kooshaba for the initial spec (https://www.notion.so/latticexyz/Ephemeral-Tables-c02a1303a93a4af29458d02c2950c266)
