### ISSUE TITLE
codegen-libdeploy won't work for IPayableSystem

### ISSUE THREAD

**Issue by bap2pecs** [latticexyz/mud#369]
`ISystem` is hardcoded in [LibDeploy.ejs](https://github.com/latticexyz/mud/blob/6fde6441c20cac58d09f3692fba2dc71d05154c2/packages/cli/src/contracts/LibDeploy.ejs) and [LibDeploy.sol](https://github.com/latticexyz/mud/blob/6fde6441c20cac58d09f3692fba2dc71d05154c2/packages/cli/src/contracts/LibDeploy.sol)

so running `mud test` gives error

```
Compiler run failed
error[7407]: TypeError: Type contract MyPayableSystem is not implicitly convertible to expected type contract ISystem.
  --> src/test/LibDeploy.sol:84:14:
   |
84 |     system = new MyPayableSystem(world, address(components));
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bap2pecs** [comment]
a possible fix:

1. in `deploy.json`, allow a new optional `payable` field for `systems`. 
2. in [LibDeploy.ejs](https://github.com/latticexyz/mud/blob/6fde6441c20cac58d09f3692fba2dc71d05154c2/packages/cli/src/contracts/LibDeploy.ejs), if this field is `true`, use `IPayableSystem`.

**Comment by dk1a** [comment]
You can use `ISystem`, have an empty `execute` which does nothing, and add the payable function you need, e.g.
```solidity
function doStuff(uint256 arg1, address arg2, ...) external payable {
...
}
```
`execute` is a bit confusing in that you don't really have to use it at the moment.
In v2 it'll be removed from the interface entirely
(https://github.com/latticexyz/mud/blob/alvrs/datamodel/packages/store/src/System.sol)
