### ISSUE TITLE
 useEntityQuery hook triggers unexpected rerenders

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#379]
Reported by @emersonhsieh

### Minimal reproduction case:
https://github.com/emersonhsieh/mud-minimal-test
https://github.com/emersonhsieh/mud-minimal-test/blob/main/packages/client/src/App.tsx

![image](https://user-images.githubusercontent.com/89248902/217410630-7b6626f4-f744-4fdc-9846-84705fa3ab30.png)

**Comment by holic** [comment]
Ahh yeah, this isn't well documented yet, but you should wrap the arguments of `useEntityQuery` in a `useMemo`:

```ts
const componentEntities = useEntityQuery(useMemo(() => [Has(components.Counter)], [components.Counter]));

```

**Comment by holic** [comment]
reminder to myself to use this for memoizing https://www.npmjs.com/package/fast-deep-equal
