### ISSUE TITLE
Proposal: React Hook for fetching data for multiple entities

### ISSUE THREAD

**Issue by emersonhsieh** [latticexyz/mud#404]
Right now useEntityQuery returns an array of entities, yet useComponentValue only takes in one entity index and can't be used in a loop. Proposal for a react hook that either fetches data for multiple entity indexes at once, or add to useEntityQuery to also return entity values alongside the indexes?

**Comment by ludns** [comment]
feel free to make a PR for this! you can probably build upon the existing hooks in thé `react` package
