### ISSUE TITLE
docs: replace hardhat/solidity-docgen with forge doc

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#431]
Since we mostly use forge over hardhat in this repo and since forge has a feature to parse docs from natspec (https://github.com/foundry-rs/foundry/issues/1675), we should revisit our solidity doc generation pipeline and potentially replace `solidity-docgen` (which requires a hardhat setup) with `forge doc`

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/pull/1762
