### ISSUE TITLE
Proposal: MUD community resource library and project pages

### ISSUE THREAD

**Issue by biscaryn** [latticexyz/mud#436]
## Motivation

Right now, information about MUD, beyond the technical documentation and guides on [mud.dev](https://mud.dev), are scattered all over the internet: one or two [“what is MUD?” talks from Devcon](https://www.youtube.com/watch?v=j-_Zf8o5Wlo&t=1039s) saved on the EF’s Youtube channel, [“how I built X on MUD” articles](https://mirror.xyz/matchboxdao.eth/SeunDJX-dFnRhTIHSF79ccYa6r6wpND0k_Si7jPqp5Y) written by community members sitting in various sites and blogs, and information about new MUD projects hiding in different Twitter pages and Discords, so on and so on.

Many in the MUD community have been asking (e.g. #343) for a unified database of MUD-related resources — articles, videos, talks — as well as an up-to-date list of projects building on MUD.

Building something like this has the potential to really grow the size of the MUD community: 

- Makes it much easier and faster for new comers to “get” the high-level picture of MUD and AW, what can be built on it, and get excited enough to actually start learning
- Gives developers the confidence to build their project on MUD by showing technical success in the real world (examples of high number of concurrent players, deployment beyond test-nets, successful projects across genres)
- Inspires exciting new projects by showing the diverse range of applications built or being built on MUD (from RTS to open worlds, on-chain scrabble to decentralized social apps)

Which would benefit all of us in the community:

- **More contributors & PRs**: more devs in the community means more contributors tackling issues and submitting PRs — more bug fixes, new features (the elusive local tx simulation?), new integrations (Unreal Engine, Godot integration?), new tools, better documentation…
- **More help:** more people building on MUD means a larger community helping you debug an error, giving useful suggestions on implementation details, design, and architecture, and more developers, artists, and designers to join you on your project
- **More resources:** more people using MUD means more learning resources — video tutorials, guides, Codeacademy-esque educational sites, which further increases adoption and puts us in a virtuous cycle

## Proposal 1: a community-managed resource library

I propose creating a community-managed resource library to host sortable, searchable, and categorizable links to articles, videos, podcasts, guides, and tutorials about MUD.

Here are some proposed design / features for an easy MVP:

- URL: [community.mud.dev](http://community.mud.dev/)
- Hosted on Notion to allow for easy MVP and editing
- Community curators collect the latest MUD resources (I can volunteer, leave a comment below if you’re also interested)
- Community members can suggest edits through Github issues and volunteer to be curators

## Proposal 2: MUD Project Pages

I propose using the same Notion set-up + [community.mud.dev](http://community.mud.dev/) as Proposal 1 to host "MUD Project Pages", where projects building on MUD can leave information about themselves.

Up for discussion, but I think some useful information would be:

- Name of project
- Genre (tags) - RTS, 4X, sandbox, open world, social app, etc.
- Tech stack (tags) - Phaser, React, Unreal, Godot, etc.
- Blurb / short description
- Team members and socials
- Links (Github repo, articles, Twitter, Discord)
- Media (screenshots, videos)
- Free text. I imagine this could be used for “community requests” — e.g. we’re looking for beta testers, frontend developers, game designers, funding
- Change log / last edited

All of this can be set up as a Notion database to allow for filtering by genre or by tech stack, so other builders and interested developers can get inspiration for design as well as implementation

## Discussion

I have a few questions for everyone to get this discussion kicked off:

1. Would people find this to be useful? If so, I can already try to build an MVP
2. **[Resource Library]** Leave a comment if you’re interested to help curate and manages MUD resources
3. **[Project Pages]** Leave a comment if you’re working on a MUD project and are interested in creating a MUD Project Page
4. **[Project Pages]** Any comments or feedback on what’s useful to have on MUD Project Pages?
5. Any other feedback, comments, or advice?

**Comment by dk1a** [comment]
Sounds very useful, I'd love to see what people are building with MUD, but don't want to spend time regularly looking for new projects.

No strong opinions on format, for me a list of links would be enough, like https://github.com/bkrem/awesome-solidity

my WIP thing: https://github.com/dk1a/wanderer-cycle (not even a minimal prototype yet, just a lot of code)

**Comment by smallbraingames** [comment]
In the history of ideas people have had, this may be one of the greatest. 

I find myself referring to whatever other MUD codebases I know of (different lattice repos, dark seas) a lot while I code, so being able to search projects, look for similar stuff, and then jump into their code would be quite useful.

Would list the projects Small Brain Games is working on. 

I wonder if this becomes a front page for people to discover different on-chain games.....

**Comment by JirAcheron** [comment]
> Would people find this to be useful? If so, I can already try to build an MVP
indeed. sounds incredibly useful

> [Resource Library] Leave a comment if you’re interested to help curate and manages MUD resources
what would this look like?

> [Project Pages] Leave a comment if you’re working on a MUD project and are interested in creating a MUD Project Page
asphodel will be releasing the source code for [kamigotchi world](https://www.youtube.com/live/RzcgrWfUhlw?feature=share&t=350) next month when we officially launch that game on Canto. we have the [Asphodel](asphodel.io) playtest, sitting somewhat stale with the incomplete game loop. we also have [Artifact](https://github.com/Asphodel-OS/Artifact), where i am personally prototyping the loot-drop / equipment-upgrade gambling loops in the open for Asphodel proper. it's debatable atm if we ever plan to invest the asset/lore effort to commercialize this one.

it seems these three fall under very different categories, but any of them could serve as useful resources for the incoming builders (once public)

> [Project Pages] Any comments or feedback on what’s useful to have on MUD Project Pages?
in general, the tagging by tech stack and genre mentioned seem really valuable as these codebases can serve as examples for incoming devs to get started quickly. as mentioned above, categorizing the projects by stage/expected commercialization effort may be helpful as well for searching and setting expectations

> Any other feedback, comments, or advice?
none atm

**Comment by proofofjake** [comment]
gm, this is almost identical to an idea I had recently! & I would be more than happy to help contribute, I've played most of the currently existing mud games (through playtests) and am very familiar with Notion if you need help in building this.

I think it could also be cool to add a calendar of future playtests, as it's currently hard to keep track of when/where these are held [split between different discord servers etc]

I also think building out this aggregated resource may allow us to identify any missing articles/explainers that could be useful to have, just adding to the beast that is mud 👍

**Comment by biscaryn** [comment]
Hey @dk1a @JirAcheron @smallbraingames, thanks for all your helpful feedback and enthusiasm about this MUD Community site!!

Two quick updates:

- @proofofjake has volunteered to be a MUD Community curator to help curate resources and create the MUD playtest schedule!
- We've built an MVP of the two proposals at [community.mud.dev](https://community.mud.dev). This is currently "soft launched" because it's live but there are no links to it on the main [mud.dev](https://mud.dev) website. 

Next steps:
- Please share any feedback you have on the current implementation of [community.mud.dev](https://community.mud.dev)
- I'll reach out individually to you guys @dk1a @JirAcheron @smallbraingames to set up your project pages
- Once we get more project pages live on there and it's in a better shape, I will open a PR to add links to it on [mud.dev](https://mud.dev) (in the top bar, references to it in the readme, etc.)

**Comment by holic** [comment]
closing this as done!
