### ISSUE TITLE
Calling Perlin.noise causes crash on contract compilation

### ISSUE THREAD

**Issue by emersonhsieh** [latticexyz/mud#439]
Minimal reproduction: 

- Clone https://github.com/emersonhsieh/mud-noise-bug
- Deploy e.g. `yarn workspace contracts dev` after devnode

<img width="579" alt="image" src="https://user-images.githubusercontent.com/2308546/221408686-d5a86ece-36cc-4781-bf10-305e70b4131d.png">

```
stderr: The application panicked (crashed).
Message:  called `Option::unwrap()` on a `None` value
Location: cli/src/cmd/forge/script/executor.rs:48

This is a bug. Consider reporting it at https://github.com/foundry-rs/foundry

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Cleaning up deployment script

-----------
Error during generateAndDeploy (see above)
```

**Comment by emersonhsieh** [comment]
Line in question is here: https://github.com/emersonhsieh/mud-noise-bug/blob/7385d80a4c4b8d806b9e7efa3a26b20851116cd8/packages/contracts/src/systems/IncrementSystem.sol#L18

**Comment by emersonhsieh** [comment]
@alvrs I also get the same error calling a public function, as shown here: 

https://github.com/emersonhsieh/mud-noise-bug/blob/539175cd58912a423f84b642c410d688baf19751/packages/contracts/src/systems/IncrementSystem.sol#L22

function in question:

```
  function testPublic() public pure returns (uint32) {
    uint32 test = 0;
    return test;
  }
```

**Comment by ludns** [comment]
I would put this in the foundry repo with a reproduction. Our contracts have broken Foundry a couple of time and they always fix it.
