### ISSUE TITLE
contracts as dependencies

### ISSUE THREAD

**Issue by dk1a** [latticexyz/mud#440]
Right now things like `forge-std` and `@solidstate/contracts` are dev+peer dependencies.
We could try making them dependencies+peerDependencies and rely on yarn's flattened node_modules to do remappings if the user didn't respect the peerDep.
One downside is I don't think this would work with pnpm, if we ever want to switch to it

Having a `mud up` command of some sort does seem like a better solution though

**Comment by holic** [comment]
is this still relevant?

**Comment by dk1a** [comment]
not really
