### ISSUE TITLE
HasValue for AddressComponent vs Uint256Component

### ISSUE THREAD

**Issue by dk1a** [latticexyz/mud#441]
`HasValue(AddressComponent, { value: playerEntityId })` expects `playerEntityId` to be checksummed
`HasValue(Uint256Component, { value: playerEntityId })` expects `playerEntityId` to be **not** checksummed

What matters here is the component schema on the contract side, and how network parses it.
At least for v2 we should normalize it

**Comment by holic** [comment]
What component type are you using on the client? I am not seeing an address one here: https://github.com/latticexyz/mud/blob/main/packages/std-client/src/components/index.ts

**Comment by dk1a** [comment]
`Entity` one (custom). Though for this issue it doesn't really matter, `defineComponent` isn't the one checksumming addresses

```typescript
import { defineComponent, Metadata, Type, World } from "@latticexyz/recs";

const Entity = {
  value: Type.Entity,
} as const;

export function defineEntityComponent<M extends Metadata>(
  world: World,
  options?: { id?: string; metadata?: M; indexed?: boolean }
) {
  return defineComponent<typeof Entity, M>(world, Entity, options);
}
```

**Comment by holic** [comment]
closing as outdated
