### ISSUE TITLE
Document how to create-mud with all package managers

### ISSUE THREAD

**Issue by roninjin10** [latticexyz/mud#512]
`npx create-mud` or `npm init mud` should use npm
`pnpm create mud` should use pnpm
`yarn create mud` should use yarn

create-wagmi then should use the selected package manager to install on project creation

**Comment by holic** [comment]
Although `create mud` now works with every package manager, we still use/expect pnpm within the project because we use pnpm's workspace features (https://github.com/latticexyz/mud/pull/599). I don't think we're going to make these templates monorepo-agnostic, so gonna close this for now.
