### ISSUE TITLE
Create linked packages for development

### ISSUE THREAD

**Issue by roninjin10** [latticexyz/mud#529]
Devs should be able to work on multiple packages without needing to fully rebuild them

https://github.com/preconstruct/preconstruct#key-features

Unlikely to use preconstruct though as it's somewhat limiting to use.   Wagmi does a tsup hack https://github.com/wagmi-dev/wagmi/blob/main/scripts/tsup.ts#L22 doing it from scratch within tsup/vite/rollup would be a light lift

If [we switch to nx](https://github.com/latticexyz/mud/issues/513), nx has their own built in ways of doing it.  Would need to gather up what the options are so the core team can decide what is best

**Comment by holic** [comment]
Is this still relevant? We now have turbo for builds and have fixed a bunch of our package build pipelines. I think there's a few packages left to migrate to e.g. tsup, but otherwise things are feeling pretty good?

**Comment by roninjin10** [comment]
Yea I don't think this is necessary and this doubles the complexity of the build pipeline.
