### ISSUE TITLE
(Easy change): Replace ts-node with tsx

### ISSUE THREAD

**Issue by roninjin10** [latticexyz/mud#530]
- tsx is easier to maintain because everything "just works!".   [See chart below ](https://github.com/privatenumber/ts-runtime-comparison)
- It's also way faster than ts-node
- Switching it is [super low risk and easy](https://github.com/ethereum-optimism/ethereum-optimism.github.io/pull/304) just replace ts-node with tsx

![image](https://user-images.githubusercontent.com/35039927/228389010-fb2d76a3-763b-4a9b-8444-3c2490f55ccb.png)

**Comment by holic** [comment]
This was done a while ago.
