### ISSUE TITLE
CLI only works in project with `ts-node` as (dev) dependency

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#538]
This currently prevents us from running the CLI via `npx` outside of a project with `ts-node` installed. Note that installing `ts-node` globally does not fix the issue.

![CleanShot 2023-03-29 at 20 04 52@2x](https://user-images.githubusercontent.com/89248902/228628527-e2196044-9479-495b-af5b-1d9bf005155c.png)

**Comment by roninjin10** [comment]
This could be a pain perpetually ideally all code that gets shipped to npm is node16 node18 compatible js
