### ISSUE TITLE
config zod should forbid solidity reserved words for e.g. field names

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#580]
Just tried something like
```
tables: {
  Test: {
    schema: {
      uint32: "uint32",
    }
  }
}
```

and it exploded on compile, should prob make this nicer with a zod validator

**Comment by dk1a** [comment]
yeah zod does no solidity keyword checks, so something like `function` would also likely cause issues at compile time. I agree zod should validate this, but it's low priority because this is an unlikely usecase and errors surface quickly

**Comment by roninjin10** [comment]
eh I kinda think the extra complexity and runtime cost (specifically to an editors ts server) of checking this with zod isn't even worth it here

**Comment by holic** [comment]
closing in favor of https://github.com/latticexyz/mud/issues/1396
