### ISSUE TITLE
Migrate internals to viem (from ethers)

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#582]
[viem](https://viem.sh/docs/introduction.html) is shaping up to be a rock solid library with [incredible benchmarks over ethers](https://viem.sh/docs/benchmarks.html). It's strongly typed, well tested, and maps closely to RPC calls and other Ethereum-native operations, and only does what you ask it to (unlike ethers that ends up doing a lot more work than is often necessary, hence benchmarks).

I've already used it in some personal projects and loving the speed/performance + predictability.

Rough plan:
- Migrate v2 store event decoding to viem
- Migrate v2 store event ingestion (rpc calls) to viem
  - We'd still lean on ethers providers for v1 things
- Build new v2 client code on top of viem

In the future:
- Use viem + wagmi for wallet connection/account delegation (pending wagmi migrating to viem)

**Comment by roninjin10** [comment]
I think a good idea here might be to wait til wagmi cli has viem plugin support.  Then you will be able to generate viem/wagmi wrappers automatically from the cli for all contracts

**Comment by holic** [comment]
This is ongoing and mostly done, things are looking quite promising! I've finally got a full WIP (#1033) running on just viem + new network packages + store-cache and we can call contracts with viem directly.
