### ISSUE TITLE
config should use paths relative to mud.config.ts (project root)

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#596]
I think in most places, any path args are relative to `mud.config.ts`, but we should firm that up as we consolidate configs.

We'll soon have a `codegenDirectory` (defaults to `codegen`) in #585 and that is now sort of implicitly coupled with `storeImportPath`, in that you need to specify or know the default codegen directory, then adjust your `storeImportPath` relative to that.

I propose we assume all paths are relative to `mud.config.ts` as a project root. So `storeImportPath` would look like
```
storeImportPath: `./src`
```
and codegen would detect this is a relative path (starts with `.`) and resolve the correct import path relative to the files being generated (`path.relative(codegenFilePath, path.join(projectRoot, storeImportPath))`)

Alternatively, for the specific issue above, we could remove the `storeImportPath` option and add a line to store's `remappings.txt` like
```
@latticexyz/store/src/=src/
```
That way imports of `@latticexyz/store/*` resolve to a local file rather than what's in e.g. node_modules

**Comment by dk1a** [comment]
> Alternatively, for the specific issue above, we could remove the storeImportPath option and add a line to store's remappings.txt like

that might be the best solution here assuming it works well for downstream consumers of store, like world

**Comment by holic** [comment]
> that might be the best solution here assuming it works well for downstream consumers of store, like world (world wouldn't need such remappings, I just need to check if store having self-referential imports is fine)

Tried this and seems to blow up downstream. It seems to work within store itself, but when world imports a store thing and store tries to import from itself, the resolution path seems to be within world rather than store?

**Comment by holic** [comment]
this is now done after some refactoring for multiple namespaces
