### ISSUE TITLE
Clean up build scripts

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#615]
We should have a consistent set of `package.json` scripts for reliable building across the monorepo. Right now, these are spread out among a few different things and doesn't consistently capture everything.

- `codegen`: should this regenerate all code? or just run mud-specific codegen? we have things like tablegen, worldgen, tsgen (hopefully being consolidated in #590) but we also have things like typechain and ts-proto
- `build`: should build everything needed to use the package locally (including codegen) and mirrors what the package from npm might look like
  - this should probably include compiling ts down to js?

If we also consolidated "steps" like "compile TS to JS", it'd help us verify that they're all using the same tooling (e.g. vite, see #612)
- `build:ts`: should compile ts to js
- `build:abi`: should build with forge and output what we need for typechain

I'm sure I am missing a bunch, but just wanted to start the convo and getting notes down.

**Comment by alvrs** [comment]
Some more thoughts:

- Some codegen commands are required for the build step (`tablegen`, `worldgen`), some have to run after the build step (`typechain`, `ts-proto`) and for some it doesn't matter `tsgen`.
- I agree that `build` should run all the necessary steps to run the package, and therefore should probably include the `codegen` steps that are required before build
- I think we should:
  * Move `tablegen` and `worldgen` to Store and World (see #616) so World and Store don't depend on CLI anymore
  * Add a `codegen` command to CLI that runs `tablegen`, `worldgen` and `tsgen` (all scripts must/can run before the build step)
  * Make sure `codegen` never depends on build output so it can always run before the build step

**Comment by holic** [comment]
> and for some it doesn't matter `tsgen`
worth noting that `tsgen` is used to generate types for components, which should be type checked along other code, so should prob be included to be part of tests (but you're right that order doesn't matter inside the build step)

**Comment by alvrs** [comment]
Linking here for context: https://github.com/latticexyz/mud/pull/620#issuecomment-1507767752

**Comment by holic** [comment]
working on this in https://github.com/latticexyz/mud/pull/633
