### ISSUE TITLE
Move `tablegen` to `Store` and `worldgen` to `World` to resolve circular dependencies

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#616]
Context in https://github.com/latticexyz/mud/pull/613#discussion_r1164263579_ :

Using `tablegen` here caused an error in the CI, because `../cli/dist/mud.js` does not exist yet while store is being built (CLI can't be built first because it depends on `World`'s ABI, which depends on `Store`). There are (at least) two approaches to solve this:
1. Move the `tablegen` scripts into `Store` (and `worldgen` scripts into `World`), so these packages can use them locally (and consumers of these packages don't have to install the MUD CLI if they only want to use eg `Store` without the rest of the framework). CLI can still expose a `tablegen` command by importing the scripts from `Store` (and a `worldgen` command by importing from `World`)
   - this may require moving common utils (render solidity) into a common package
2. Check in the World/Store ABIs, so CLI can be built independently from building World/Store (this alone doesn't fix the circular dependency though)

**Comment by holic** [comment]
I burned a bunch of time today on the circular dependency (cli <> world/store) issue again while working on https://github.com/latticexyz/mud/pull/620. So I'm eager to get this fixed so we don't have to fight this anymore.

**Comment by holic** [comment]
done in https://github.com/latticexyz/mud/commit/60e62ebf70b0fe2fce39cd15b3d5b46120c34dd4
