### ISSUE TITLE
Add linter for consistent package.json key order

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#617]
The formatting of our package.json files are all over the place but I'd prefer we set up an automated linter/fixer for this rather than manually fixing/maintaining.

I tried to do this with [eslint-plugin-package-json](https://github.com/zetlen/eslint-plugin-package-json) but it had issues, seemingly related to parsing JSON? eslint should be capable of parsing JSON so not sure what's up, maybe a version mismatch issue or something.

**Comment by alvrs** [comment]
closed via #627
