### ISSUE TITLE
Bug: cannot write many bytes to tables with tableIdArgument

### ISSUE THREAD

**Issue by yonadaaa** [latticexyz/mud#676]
### To replicate:

Declare a table with `tableIdArgument`, any primary keys, and a `bytes` field.

```
TestTable: {
    primaryKeys: {},
    schema: "bytes",
    tableIdArgument: true,
},
```

Writing a four character string is okay:
`TestTable.set(world, RangeTableId, bytes("1234"));`

But writing more, like:
`TestTable.set(world, RangeTableId, bytes("12345"));`

results in `StoreCore_InvalidDataLength(4, 5)` error.

**Comment by dk1a** [comment]
I think the problem is with where RangeTableId comes from, and how the schema at that location is registered, so I need that context too

**Comment by holic** [comment]
ooc what does the `TestTable` generated code/function signatures look like?

**Comment by yonadaaa** [comment]
@dk1a I think the table should be registered as I'm using this in a test (but I don't have the best understand of how schemas work). The full context is like: 

```
contract MyTest is MudV2Test {
  IWorld world;

  function setUp() public override {
    super.setUp();
    world = IWorld(worldAddress);
  }

  function testBytes() public {
    vm.startPrank(address(world));

    TestTable.set(world, RangeTableId, bytes("12345"));
  }
}
```

**Comment by yonadaaa** [comment]
@holic sure, and I will create a minimal repo to demo this. The `set` function is like:
```
function set(bytes32 _tableId, bytes memory value) internal {
  bytes32[] memory _primaryKeys = new bytes32[](0);

  StoreSwitch.setField(_tableId, _primaryKeys, 0, bytes((value)));
}
  ```

**Comment by dk1a** [comment]
> @dk1a I think the table should be registered as I'm using this in a test (but I don't have the best understand of how schemas work). I've not had issues with Table.set() in any other tests.

I kinda forgot `test-v2` existed, you need `.registerSchema` if you're running pure `forge test`, or deploying stuff dynamically during tests (which is what my minimal example was, I just registered a new schema during `forge test`)

> Range has two int32 fields. If I use a single uint256 field, I get StoreCore_InvalidDataLength(4, 32). Am I just misunderstanding how tableIdArgument works and it is writing to the Range table?

yeah it is writing to the Range table. Which has an underlying immutable schema (in your case it's 2 int32s), and no matter which lib you use it all goes through `StoreCore`, which checks the data against the schema. And your schema doesn't allow more than 4 bytes (2 for each int32), so the error is expected.

Gave the skystrife's convert-mudv2 branch a look. I think your use of `StoreSwitch` directly is the right way to go about this. And to initially set factory data you'd use the appropriate table's `encode` to get the correct tightly encoded bytes

**Comment by yonadaaa** [comment]
Okay great, thanks for clearing this all up. This is definitely NOT a bug. I just made `tableIdArgument` into a footgun by not really understanding what it does. 

Glad the Factories implementation check out. I will just use a `bytes32` primaryKey to represent the tableId.

Closing this issue, thanks all!
