### ISSUE TITLE
[Client] Dev UI (observability into mud internals)

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#705]
General idea:

- Allow developers to inspect their contract state, see state updates, see transactions and their status, see other metadata about their client (whether sync happens from rpc/mode, sync status, connected address)
- On a high level there are two approaches:
  1. a separate dashboard to show the infos above
  2. UI imported in the client to show the infos above

We could combine the two approaches by:
- Creating a couple standard React components that can be used in clients (for development or simple UI)
  - Transaction queue
  - Table data visualization
  - Toasts for store updates, errors, transaction success/failure
  - Metadata like connected address, balance, sync status, block number
- Plugging these components together in a standalone client that can be connected to any MUD World/store

Why do we need all this? The Aha moment for MUD comes when your UI syncs with your contract and you didn’t have to do anything! With this dev UI + a way to call systems without UI, people can get to that moment in 10 minutes or less!

**Comment by holic** [comment]
This was shipped!
