### ISSUE TITLE
[CLI] Decode custom errors in forge and client

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#712]
Currently custom errors are not correctly decoded in forge tests or the client, but only surfaced as `bytes4` selector

**Comment by holic** [comment]
Might be fixed by https://github.com/latticexyz/mud/pull/767 and https://github.com/latticexyz/mud/pull/768

**Comment by holic** [comment]
I did see this pop up recently in some foundry tests, so I think this is fixed.



![Image](https://github.com/latticexyz/mud/assets/508855/21d6351b-a112-411b-97f9-33a013d637fc)
