### ISSUE TITLE
[MODE] Fix type conversions for bytes and strings and add tests

### ISSUE THREAD

**Issue by authcall** [latticexyz/mud#716]
- Swap out ORM
- Rewrite to have better interface when inserting and when fetching to send back to client (but before abi.encoding to bytes)
- Add helpers to transform internal schema -> dynamic struct 
- Use dynamic struct instead of sql builders for insert / update / delete as currently done
- Add tests for everything

**Comment by alvrs** [comment]
done in https://github.com/latticexyz/mud/pull/645
