### ISSUE TITLE
[Docs] user-facing recs documentation

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#721]
Quality over quantity - add user facing docs for:

- [ ] Stuff in `Component.ts` (`defineComponent`, `setComponent`, etc)
- [ ] `createEntity`
- [ ] `createWorld`
- [ ] Stuff in `System.ts` (`defineSystem`, etc)

(No need to document all the internal workings, just the surface area)

**Comment by holic** [comment]
https://mud.dev/state-query/typescript/recs
