### ISSUE TITLE
Rename `popFromField` to `removeFromField` or `dropFromField`

### ISSUE THREAD

**Issue by dk1a** [latticexyz/mud#737]

**Comment by alvrs** [comment]
Currently we don't need to read the popped data from storage; if we wanted to return it we had to read from storage, so maybe we shouldn't add this. (Maybe we should change the name to something like "removeElement" to make it clearer)

**Comment by alvrs** [comment]
Can't find naming i'm happy with. "append/add/truncate/remove" are all less intuitive than "push/pop", except that the "pop" method doesn't return anything

**Comment by alvrs** [comment]
let's keep push/pop
