### ISSUE TITLE
Replace lodash utilities with esm-compatible utilities

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#743]
`setupMUDV2Network` doesn't work in a node environment because lodash isn't esm compatible. This results in issues like this:
![image](https://user-images.githubusercontent.com/71292860/236423445-333c29ce-c09d-414f-9502-039561245f9d.png)

I propose lodash is replaced with another library that is esm compatible, or custom utility functions are written to replace its functionality. (this would also save on package size)

**Comment by holic** [comment]
I think we've removed pretty much all usages of lodash
