### ISSUE TITLE
docs: Edit buttons on docs website takes user to old MUD folder on Github that gives 404 error

### ISSUE THREAD

**Issue by ltfschoen** [latticexyz/mud#819]
If I go to https://mud.dev/guides/getting_started/, at the bottom of the page there's a link to edit the docs "1.42.0"` that refers to the current version

<img width="323" alt="Screen Shot 2023-05-15 at 8 43 41 am" src="https://github.com/latticexyz/mud/assets/6226175/b1314df3-4e13-471b-ac84-21b0048f9c26">

But if I click the link it takes me to https://github.com/latticexyz/mud/blob/main/guides/getting_started.md, which returns 404 - page not found

That appears to be because the docs have now moved into a subdirectory https://github.com/latticexyz/mud/blob/main/docs/pages/guides/getting_started.md

**Comment by holic** [comment]
this was fixed a while ago
