### ISSUE TITLE
Request the generated DApp to have custom script in package.json that exposes custom host value

### ISSUE THREAD

**Issue by ltfschoen** [latticexyz/mud#859]
I have setup the Foundry and MUD v2 stack to all run in a Docker container using Debian and expose port 3000 and 8545 so the user can view a DApp on their host machine (i.e. macOS) at http://localhost:3000

But to achieve that, after generating an example project with:
```
pnpm config set store-dir ~/pnpm
pnpm create mud@canary my-first-mud-project
cd my-first-mud-project
```
I then had to modify its package.json file manually to add ` --host 0.0.0.0` so it change to 
```json
  "scripts": {
    ...
    "dev:client": "pnpm --filter 'client' run dev --host 0.0.0.0",
```
So then when i ran the DApp with:
```bash
rm -rf node_modules
pnpm install --global run-pty
pnpm install
pnpm initialize
pnpm run dev
```
It then showed green lights in the dashboard and if i selected [2] for pnpm dev:client it output:
```bash
  VITE v4.2.1  ready in 6407 ms


[ctrl+c] kill (pid 469)
[ctrl+z] dashboard
                    ➜  Local:   http://localhost:3000/

[ctrl+c] kill (pid 469)
[ctrl+z] dashboard
                    ➜  Network: http://172.17.0.2:3000/
```
So then i was able to to go to http://localhost:3000 in the browser on my host machine to view the DApp successfully.

But I don't think it should be necessary to do that manually. If i didn't modify the package.json file, then when i run `pnpm run dev`, and then click [2] in the dashboard, it outputs:

```bash
  VITE v4.2.1  ready in 12032 ms


[ctrl+c] kill (pid 40)
[ctrl+z] dashboard
                    ➜  Local:   http://localhost:3000/

[ctrl+c] kill (pid 40)
[ctrl+z] dashboard
                    ➜  Network: use --host to expose

[ctrl+c] kill (pid 40)
[ctrl+z] dashboard
                    ➜  press h to show help
```

Note how it says `Network: use --host to expose`?
But if I can't just run ``pnpm run dev --host 0.0.0.0` from the CLI, it has to be added in package.json.

Could we please update the package.json that is generated so it is like this maybe:
```json
    "dev": "run-pty % pnpm dev:node % pnpm dev:client % pnpm dev:contracts",
    "dev-custom-host": "run-pty % pnpm dev:node % pnpm dev:client-custom-host % pnpm dev:contracts",
    "dev:client": "pnpm --filter 'client' run dev",
    "dev:client-custom-host": "pnpm --filter 'client' run dev --host 0.0.0.0",
    "dev:contracts": "pnpm --filter 'contracts' dev",
    "dev:node": "pnpm --filter 'contracts' devnode",
```
Or possibly even make the `--host` value an environment variable so users could run `export CUSTOM_HOST=0.0.0.0 && pnpm run dev-custom-host`

**Comment by holic** [comment]
The templates just use plain Vite in `packages/client`, so you can add `--host` flag to the `dev` script in `packages/client/package.json` (or any other vite CLI args)

**Comment by ltfschoen** [comment]
Yes, I agree, would be good if it was in the MUD v2 docs since I don't recall the current docs mentioning that Vite.js was being used (since it does stuff behind the scenes)

**Comment by holic** [comment]
We're about to expand on our quick start guide, which covers some of the file layout + technical choices of the templates, so we'll be sure to add a note about using Vite as our client builder/runner.
