### ISSUE TITLE
clean up stale branches

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#873]
Maybe there's a tool for this already but we should figure out how to delete all the branches from merged PRs to clean up the list of branches in the repo and the cost of cloning/pulling down the fresh codebase.

**Comment by yonadaaa** [comment]
Looks like there is a GitHub setting https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-the-automatic-deletion-of-branches

**Comment by holic** [comment]
Enabled! Would still like to clean up old ones.

**Comment by holic** [comment]
Done!
