### ISSUE TITLE
dev-contracts follow up

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#880]
- [x] a typo in mud config breaks the runner/watcher, should prob watch everything that isn't the file watcher in a try/catch so we can retry even after bad config changes
- [x] adding an enum didn't seem to retrigger the codegen + deploy process?
- [x] changing PostDeploy didn't seem to redeploy
- [ ] lots of duplicate behavior inside dev-contracts as in template scripts (initialize, etc.), can we consolidate?

**Comment by holic** [comment]
I think this is ~done?

**Comment by alvrs** [comment]
the first point is open again but tracked in https://github.com/latticexyz/mud/issues/1731
