### ISSUE TITLE
Update to `concurrently` instead of `node-pty` appears to have introduce CORS issues temporarily until fully loaded

### ISSUE THREAD

**Issue by ltfschoen** [latticexyz/mud#916]
Prior to the updates that were made to https://github.com/latticexyz/mud/tree/main/templates/react (i.e. https://github.com/latticexyz/mud/commit/e84dc42a7e649a58d3c4ab257c74bf1477f14600 and https://github.com/latticexyz/mud/commit/47ab35d746b174be806d633699e7ef7570052ce4#diff-875645c368e4f255be02679e9bc3cc6b197c8e52b18ed33e67c27ffab4365a64L6) where the use of `run-pty` was replaced with the use of `concurrently` (i.e. before `"dev": "run-pty % pnpm dev:node % pnpm dev:client % pnpm dev:contracts",` was replaced with `"dev": "concurrently \"cd packages/contracts && pnpm run dev\" \"cd packages/client && pnpm run dev\"",`, when I ran `export ANVIL_IP_ADDR=0.0.0.0 && pnpm run dev` it would not generate any CORS errors in the browser console logs.

However since that change was made, now when I follow the steps in this README https://github.com/ltfschoen/MUDTest#create-new-project-, where I use a run.sh script that replaces:
```
"dev": "concurrently \"cd packages/contracts && pnpm run dev\" \"cd packages/client && pnpm run dev\"",
``` 
with 
```
"dev": "concurrently \"cd packages/contracts && export ANVIL_IP_ADDR=0.0.0.0 && pnpm run dev\" \"cd packages/client && export ANVIL_IP_ADDR=0.0.0.0 && pnpm run dev\"",
```
and now just run it with `pnpm run dev`,
to try to avoid any CORS issues like i was able to before, when it gets to the stage where the dev:client shows what endpoint to use to open it in the browser, it shows the following CORS error (it didn't do that before).

<img width="1140" alt="Screen Shot 2023-05-19 at 9 03 37 am" src="https://github.com/latticexyz/mud/assets/6226175/1d297b40-ba95-4e53-ac5c-5df0b8c05b93">

But if I keep waiting until the terminal logs are as shown below, then the CORS error disappears and it successfully loads the page

<img width="1131" alt="Screen Shot 2023-05-19 at 9 06 16 am" src="https://github.com/latticexyz/mud/assets/6226175/44f69c78-90e7-456b-9043-b8dca5a3495f">

**Comment by holic** [comment]
I'm planning to make the client a bit more robust for these cases, but in the meantime, have you tried using the `wait-port` approach we have in client templates? 
https://github.com/latticexyz/mud/blob/9e98a81c5d6650a785c663c9a25e34a6d9b196d8/templates/react/packages/client/package.json#L9

**Comment by ltfschoen** [comment]
> wait-port

cool, so i could try maybe changing it to 
```
"dev": "concurrently \"cd packages/contracts && export ANVIL_IP_ADDR=0.0.0.0 && pnpm run dev\" \"cd packages/client && wait-port localhost:8545 && export ANVIL_IP_ADDR=0.0.0.0 && pnpm run dev\"",
```
or use `wait-port 0.0.0.0:8545` instead of `wait-port localhost:8545`

**Comment by ltfschoen** [comment]
> wait-port localhost:8545

yes using `wait-port localhost:8545` worked perfectly, now it only loads the page when that port is ready
