### ISSUE TITLE
Feedback for “Interacting with MUD from a client”

### ISSUE THREAD

**Issue by rsodre** [latticexyz/mud#924]
Hello!

I found some issues on the [client-side](https://mud.dev/client-side) doc page

* The [Edit this page](https://github.com/latticexyz/mud/blob/core/docs/pages/pages/client-side.mdx) link does not work

* This...
```
const { storeCache } = useMUD;
```
should be...
```
const {
  network: { storeCache },
} = useMUD();
```

**Comment by holic** [comment]
closing as outdated
