### ISSUE TITLE
dev/anvil: bubble up `console.log` and other signalful anvil logs

### ISSUE THREAD

**Issue by holic** [latticexyz/mud#927]
`dev-contracts` currently swallows these

**Comment by holic** [comment]
since we have mprocs, we can just spin up local anvil as a separate process, then use the local anvil rpc url in the dev contracts command

**Comment by rencryptofish** [comment]
did you happen to find a workaround for this by chance? i'm running into a similar issue, can't see the forge std logs

**Comment by holic** [comment]
you can work around by running anvil separately (in another terminal window, for example) then use that rpc url for the dev-contracts/deploy step
