### ISSUE TITLE
Dev Tools don't show MODE connection

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#929]
Just noticed the dev tools still show "MODE unavailable" even if the client is syncing via MODE

<img width="1208" alt="CleanShot 2023-05-20 at 09 18 09@2x" src="https://github.com/latticexyz/mud/assets/89248902/96a33281-00ca-4e89-b363-6655ae77a6b9">

**Comment by holic** [comment]
whoops, I never wired this up 🙈

**Comment by holic** [comment]
I got rid of this in https://github.com/latticexyz/mud/pull/1284
