### ISSUE TITLE
Allow tables to be used in tests without providing explicit store argument

### ISSUE THREAD

**Issue by dk1a** [latticexyz/mud#940]
This is especially a problem for libraries that use tables - having to manually pass worldAddress in all custom lib methods is bad devex
Making systems specifically for tests is an option of course, but also rather inconvenient and unnecessary in many cases

1. One solution is to call tests with msg.sender equal to worldAddress (as if they're systems), and also startPrank(worldAddress) in tests to bypass AccessControl (as if whenever tests call world, it's like world calls itself, e.g. a root system).

2. Another solution would be to change how StoreSwitch detects store, for example instead of `isStore` have a method that actually returns storeAddress

3. Or we can double down on systems for tests, and not do this. I'm not entirely certain spoofing world in tests is the best idea

**Comment by alvrs** [comment]
when we touch `isStore` for approach 2 we should also fix this one: https://github.com/latticexyz/mud/pull/540 (if we stick with a method, then just passing fixed amount of gas)
