### ISSUE TITLE
reduce size of `@latticexyz/services`

### ISSUE THREAD

**Issue by alvrs** [latticexyz/mud#947]
currently developers have to download almost 40mb for the services package during `pnpm install` in a mud project. We should reduce this size, eg by splitting the package into `services-go` and `services-ts` (so consumers only need to install the slim ts package)
<img width="712" alt="CleanShot 2023-05-22 at 13 43 12@2x" src="https://github.com/latticexyz/mud/assets/89248902/ba3d2f5b-1504-408d-8cec-218c78467720">

**Comment by holic** [comment]
~done in #1635
