### ISSUE TITLE
Allow optional constructor arguments in mud config and system deployment script

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#977]
There is no way for the system to know its own namespace, so I am trying to pass the namespace into the system's constructor to store it in the system's local storage. However, it is currently impossible to define constructor parameters in the world.

**Comment by dk1a** [comment]
note that root systems are delegatecalled, so you shouldn't be having state in systems. I guess it could work if u're certain that the system can never be installed in root, but it's likely possible to store that state somewhere else instead.

regarding namespace specifically, you could always get it but it requires excessive understanding of MUD internals, so https://github.com/latticexyz/mud/pull/979 adds a convenient helper

**Comment by 0xhank** [comment]
that is what i need!

**Comment by alvrs** [comment]
Fixed by #979
