### ISSUE TITLE
Proposal: Change `pnpm initialize` to `pnpm prep`

### ISSUE THREAD

**Issue by 0xhank** [latticexyz/mud#997]
`pnpm init` is already a highly used command and `pnpm prep` saves me six letters whenever I type it. It also fits the script's purpose better

**Comment by dk1a** [comment]
could we just make 1 `build` command for templates, like in https://github.com/latticexyz/mud/blob/main/integration-sandbox/packages/contracts/package.json ?
template scripts seem rather complicated rn

**Comment by holic** [comment]
yeah I would prefer to merge it into `build` and avoid overloading init vs initialize and prep vs prepare
